"use client"

import type React from "react"

import { createContext, useContext, useState } from "react"

type Language = "IT" | "EN" | "DE" | "BS" | "RU" | "CZ" | "AL"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const languages = {
  IT: { flag: "🇮🇹", name: "Italiano" },
  EN: { flag: "🇬🇧", name: "English" },
  DE: { flag: "🇩🇪", name: "Deutsch" },
  BS: { flag: "🇧🇦", name: "Bosanski" },
  RU: { flag: "🇷🇺", name: "Русский" },
  CZ: { flag: "🇨🇿", name: "Čeština" },
  AL: { flag: "🇦🇱", name: "Shqip" },
}

const translations = {
  "nav.home": { IT: "Home", EN: "Home", DE: "Startseite", BS: "Početna", RU: "Главная", CZ: "Domů", AL: "Kryefaqja" },
  "nav.about": {
    IT: "Chi Siamo",
    EN: "About Us",
    DE: "Über uns",
    BS: "O nama",
    RU: "О нас",
    CZ: "O nás",
    AL: "Rreth nesh",
  },
  "nav.menu": { IT: "Menu", EN: "Menu", DE: "Speisekarte", BS: "Meni", RU: "Меню", CZ: "Menu", AL: "Menyja" },
  "nav.gallery": {
    IT: "Galleria",
    EN: "Gallery",
    DE: "Galerie",
    BS: "Galerija",
    RU: "Галерея",
    CZ: "Galerie",
    AL: "Galeria",
  },
  "nav.contact": {
    IT: "Contatti",
    EN: "Contact",
    DE: "Kontakt",
    BS: "Kontakt",
    RU: "Контакты",
    CZ: "Kontakt",
    AL: "Kontakti",
  },

  "hero.welcome": {
    IT: "BENVENUTI PRESSO",
    EN: "WELCOME TO",
    DE: "WILLKOMMEN BEI",
    BS: "DOBRODOŠLI U",
    RU: "ДОБРО ПОЖАЛОВАТЬ В",
    CZ: "VÍTEJTE V",
    AL: "MIRË SE VINI NË",
  },
  "hero.subtitle": {
    IT: "Un locale rinnovato che vi accoglie con calore e vi coccola con i sapori del territorio, per trasformare ogni momento di relax in un piacere autentico.",
    EN: "A renovated venue ready to welcome and pamper you in a warm and welcoming atmosphere, accompanying you with a selection of local products to make your moments of relaxation comfortable.",
    DE: "Ein renoviertes Lokal, bereit Sie in warmer und einladender Atmosphäre zu empfangen und zu verwöhnen, begleitet von einer Auswahl regionaler Produkte für entspannte Momente.",
    BS: "Obnovljeni lokal spreman da vas dočeka i mazi u toploj i gostoljubivoj atmosferi, prateći vas izborom lokalnih proizvoda za ugodne trenutke opuštanja.",
    RU: "Обновленное заведение готово принять и побаловать вас в теплой и гостеприимной атмосфере, предлагая отборные местные продукты для комфортного отдыха.",
    CZ: "Zrekonstruovaný podnik připravený vás uvítat a rozmazlovat v teplé a příjemné atmosféře, doprovázet vás výběrem místních produktů pro pohodlné chvíle odpočinku.",
    AL: "Një lokal i rinovuar i gatshëm t'ju presë dhe t'ju përkëdhelë në një atmosferë të ngrohtë dhe mikpritëse, duke ju shoqëruar me një përzgjedhje produktesh lokale për t'i bërë momentet tuaja të relaksit komode.",
  },
  "hero.discover": {
    IT: "Scopri di Più",
    EN: "Discover More",
    DE: "Mehr entdecken",
    BS: "Otkrijte više",
    RU: "Узнать больше",
    CZ: "Objevte více",
    AL: "Zbuloni më shumë",
  },

  "about.title": {
    IT: "La Nostra Storia",
    EN: "Our Story",
    DE: "Unsere Geschichte",
    BS: "Naša priča",
    RU: "Наша история",
    CZ: "Náš příběh",
    AL: "Historia jonë",
  },
  "about.description": {
    IT: "Immerso nella bellezza delle montagne, La Busa del Sauc rappresenta l'essenza della tradizione culinaria locale. Ogni piatto racconta una storia, ogni sapore evoca ricordi di antiche ricette tramandate di generazione in generazione.",
    EN: "Immersed in the beauty of the mountains, La Busa del Sauc represents the essence of local culinary tradition. Every dish tells a story, every flavor evokes memories of ancient recipes passed down from generation to generation.",
    DE: "Eingebettet in die Schönheit der Berge repräsentiert La Busa del Sauc die Essenz der lokalen kulinarischen Tradition. Jedes Gericht erzählt eine Geschichte, jeder Geschmack weckt Erinnerungen an alte Rezepte, die von Generation zu Generation weitergegeben wurden.",
    BS: "Ubiveni u ljepotu planina, La Busa del Sauc predstavlja osnovu lokalne kulinarske tradicije. Svako jelo priča priču, svaki okus podigne sjećanje na drevne recepte prenošene od generacije na generaciju.",
    RU: "Погруженный в красоту гор, La Busa del Sauc представляет суть местной кулинарной традиции. Каждое блюдо рассказывает историю, каждый вкус вызывает воспоминания о древних рецептах, передаваемых из поколения в поколение.",
    CZ: "Ponořen do krásy hor, La Busa del Sauc představuje podstatu místní kulinářské tradice. Každé jídlo vypráví příběh, každá chuť vyvolává vzpomínky na staré recepty předávané z generace na generaci.",
    AL: "Përshëndetetje nëpër ljeposinë e planinave, La Busa del Sauc përshkruan oshtinë e tradicioneve kulinare të vendit. Çdo jelo dëshiron një histori, çdo flasë kërkon sjeçtje për receptet tradicionale të vjetër të pasur nga një generacion në tjetrin.",
  },
  "atmosphere.title": {
    IT: "Atmosfera Accogliente",
    EN: "Welcoming Atmosphere",
    DE: "Einladende Atmosphäre",
    BS: "Ugodna atmosfera",
    RU: "Уютная атмосфера",
    CZ: "Příjemná atmosféra",
    AL: "Atmosferë mikpritëse",
  },
  "atmosphere.description1": {
    IT: "Il nostro locale rinnovato mantiene il calore e l'autenticità della tradizione montana, offrendo un ambiente dove ogni ospite si sente a casa. L'arredamento in legno naturale e i dettagli curati creano l'atmosfera perfetta per momenti indimenticabili.",
    EN: "Our renovated venue maintains the warmth and authenticity of mountain tradition, offering an environment where every guest feels at home. Natural wood furnishings and carefully crafted details create the perfect atmosphere for unforgettable moments.",
    DE: "Unser renoviertes Lokal bewahrt die Wärme und Authentizität der Bergtradition und bietet eine Umgebung, in der sich jeder Gast wie zu Hause fühlt. Natürliche Holzmöbel und sorgfältig gestaltete Details schaffen die perfekte Atmosphäre für unvergessliche Momente.",
    BS: "Naš obnovljeni lokal zadržava toplinu i autentičnost planinske tradicije, nudeći okruženje u kojem se svaki gost osjeća kao kod kuće. Prirodni drveni namještaj i pažljivo osmišljeni detalji stvaraju savršenu atmosferu za nezaboravne trenutke.",
    RU: "Наше обновленное заведение сохраняет тепло и подлинность горных традиций, предлагая среду, где каждый гость чувствует себя как дома. Натуральная деревянная мебель и тщательно продуманные детали создают идеальную атмосферу для незабываемых моментов.",
    CZ: "Náš zrekonstruovaný podnik si zachovává teplo a autenticitu horské tradice, nabízí prostředí, kde se každý host cítí jako doma. Přírodní dřevěný nábytek a pečlivě navržené detaily vytvářejí dokonalou atmosféru pro nezapomenutelné chvíle.",
    AL: "Lokali rinovuar i gatshëm t'ju mbahet nga tepër dhe nga oshtinë e tradicioneve të planinave, duke ofruar një mjedisje ku çdo vizitor se duhet si në shtëpia. Mobiliat e drejtshënë dhe detajet e paqartëshme krijojnë atmosferë të perfekte për momentet e paqartëshme.",
  },
  "atmosphere.description2": {
    IT: "Dalla colazione al dopocena, vi accompagniamo con prodotti selezionati del territorio, vini pregiati e specialità che celebrano i sapori autentici della nostra terra.",
    EN: "From breakfast to after-dinner, we accompany you with selected local products, fine wines and specialties that celebrate the authentic flavors of our land.",
    DE: "Vom Frühstück bis zum Digestif begleiten wir Sie mit ausgewählten regionalen Produkten, edlen Weinen und Spezialitäten, die die authentischen Aromen unserer Heimat feiern.",
    BS: "Od doručka do večere, pratimo vas odabranim lokalnim proizvodima, finim vinima i specijalitetima koji slave autentične okuse naše zemlje.",
    RU: "От завтрака до ужина мы сопровождаем вас отборными местными продуктами, изысканными винами и деликатесами, которые прославляют подлинные вкусы нашей земли.",
    CZ: "Od snídaně po večeři vás doprovázíme vybranými místními produkty, kvalitními víny a specialitami, které oslavují autentické chutě naší země.",
    AL: "Nga mëngjesi deri në veprimtari, ju shoqëruam me produktet e zgjedhur nga vendi, vinat e mirë dhe specialitetet që flasojnë vlerat e vetme të vendit tanë.",
  },
  "menu.title": {
    IT: "Il Nostro Menu",
    EN: "Our Menu",
    DE: "Unsere Speisekarte",
    BS: "Naš meni",
    RU: "Наше меню",
    CZ: "Naše menu",
    AL: "Menyja jonë",
  },
  "menu.description": {
    IT: "Scoprite i sapori autentici della tradizione montana attraverso i nostri piatti preparati con ingredienti freschi e di qualità del territorio.",
    EN: "Discover the authentic flavors of mountain tradition through our dishes prepared with fresh, quality local ingredients.",
    DE: "Entdecken Sie die authentischen Aromen der Bergtradition durch unsere Gerichte, die mit frischen, hochwertigen regionalen Zutaten zubereitet werden.",
    BS: "Otkrijte autentične okuse planinske tradicije kroz naše jela pripremljena sa svježim, kvalitetnim lokalnim sastojcima.",
    RU: "Откройте для себя подлинные вкусы горных традиций через наши блюда, приготовленные из свежих, качественных местных ингредиентов.",
    CZ: "Objevte autentické chutě horské tradice prostřednictvím našich jídel připravených z čerstvých, kvalitních místních ingrediencí.",
    AL: "Zbuloni vlerat e vetme të tradicioneve të planinave përmes dishave tanë të parapetuar me sastojët e frasha dhe të cilësuar nga vendi.",
  },
  "menu.antipasti": {
    IT: "Antipasti",
    EN: "Appetizers",
    DE: "Vorspeisen",
    BS: "Predjela",
    RU: "Закуски",
    CZ: "Předkrmy",
    AL: "Antipasti",
  },
  "menu.primi": {
    IT: "Primi Piatti",
    EN: "First Courses",
    DE: "Erste Gänge",
    BS: "Prva jela",
    RU: "Первые блюда",
    CZ: "První chody",
    AL: "Primi Piatti",
  },
  "menu.secondi": {
    IT: "Secondi Piatti",
    EN: "Main Courses",
    DE: "Hauptgerichte",
    BS: "Glavna jela",
    RU: "Основные блюда",
    CZ: "Hlavní chody",
    AL: "Secondi Piatti",
  },
  "menu.contorni": {
    IT: "Contorni",
    EN: "Side Dishes",
    DE: "Beilagen",
    BS: "Prilozi",
    RU: "Гарниры",
    CZ: "Přílohy",
    AL: "Contorni",
  },
  "menu.bevande": {
    IT: "Bevande",
    EN: "Beverages",
    DE: "Getränke",
    BS: "Pića",
    RU: "Напитки",
    CZ: "Nápoje",
    AL: "Beverages",
  },
  "gallery.title": {
    IT: "Galleria",
    EN: "Gallery",
    DE: "Galerie",
    BS: "Galerija",
    RU: "Галерея",
    CZ: "Galerie",
    AL: "Galeria",
  },
  "gallery.description": {
    IT: "Un viaggio visivo attraverso i nostri piatti e l'atmosfera unica del nostro ristorante.",
    EN: "A visual journey through our dishes and the unique atmosphere of our restaurant.",
    DE: "Eine visuelle Reise durch unsere Gerichte und die einzigartige Atmosphäre unseres Restaurants.",
    BS: "Put vizualisht nëpër dishave tanë dhe atmosferën unikë të restorantit tanë.",
    RU: "Визуальное путешествие по нашим блюдам и уникальной атмосфере нашего ресторана.",
    CZ: "Vizuální cesta našimi jídly a jedinečnou atmosférou naší restaurace.",
    AL: "Një udhëhtje vizualisht nëpër dishave tanë dhe atmosferën unikë të restorantit tanë.",
  },
  "contact.title": {
    IT: "Contatti",
    EN: "Contact",
    DE: "Kontakt",
    BS: "Kontakt",
    RU: "Контакты",
    CZ: "Kontakt",
    AL: "Kontakti",
  },
  "contact.description": {
    IT: "Siamo qui per accogliervi e rendere speciale ogni vostro momento con noi.",
    EN: "We are here to welcome you and make every moment with us special.",
    DE: "Wir sind hier, um Sie willkommen zu heißen und jeden Moment mit uns besonders zu machen.",
    BS: "Tu smo da vas dočekamo i učinimo svaki trenutak s nama posebnim.",
    RU: "Мы здесь, чтобы приветствовать вас и сделать каждый момент с нами особенным.",
    CZ: "Jsme tu, abychom vás přivítali a učinili každý okamžik s námi výjimečným.",
    AL: "Janë tani për të presë dhe të bërë çdo moment të tuaj të vërtetë me ne.",
  },
  "contact.address": {
    IT: "Indirizzo",
    EN: "Address",
    DE: "Adresse",
    BS: "Adresa",
    RU: "Адрес",
    CZ: "Adresa",
    AL: "Adresa",
  },
  "contact.hours": {
    IT: "Orari",
    EN: "Hours",
    DE: "Öffnungszeiten",
    BS: "Radno vrijeme",
    RU: "Часы работы",
    CZ: "Otevírací doba",
    AL: "Orari",
  },
  "contact.phone": {
    IT: "Telefono & WhatsApp",
    EN: "Phone & WhatsApp",
    DE: "Telefon & WhatsApp",
    BS: "Telefon & WhatsApp",
    RU: "Телефон и WhatsApp",
    CZ: "Telefon & WhatsApp",
    AL: "Telefon & WhatsApp",
  },
  "contact.follow": {
    IT: "Seguici",
    EN: "Follow Us",
    DE: "Folgen Sie uns",
    BS: "Pratite nas",
    RU: "Следите за нами",
    CZ: "Sledujte nás",
    AL: "Sledoni ne",
  },
  "contact.priceRange": {
    IT: "Fascia di Prezzo",
    EN: "Price Range",
    DE: "Preisklasse",
    BS: "Cjenovni razred",
    RU: "Ценовая категория",
    CZ: "Cenová kategorie",
    AL: "Ranësia e çmimit",
  },
  "contact.perPerson": {
    IT: "per persona",
    EN: "per person",
    DE: "pro Person",
    BS: "po osobi",
    RU: "на человека",
    CZ: "na osobu",
    AL: "për person",
  },
  "contact.reservationInfo": {
    IT: "Per prenotazioni e informazioni, contattateci via WhatsApp al numero sopra indicato. Saremo lieti di accogliervi nella nostra atmosfera montana autentica.",
    EN: "For reservations and information, contact us via WhatsApp at the number above. We will be happy to welcome you to our authentic mountain atmosphere.",
    DE: "Für Reservierungen und Informationen kontaktieren Sie uns über WhatsApp unter der oben angegebenen Nummer. Wir freuen uns darauf, Sie in unserer authentischen Bergatmosphäre willkommen zu heißen.",
    BS: "Za rezervacije i informacije kontaktirajte nas putem WhatsApp-a na gore navedeni broj. Rado ćemo vas dočekati u našoj autentičnoj planinskoj atmosferi.",
    RU: "Для бронирования и информации свяжитесь с нами через WhatsApp по указанному выше номеру. Мы будем рады приветствовать вас в нашей подлинной горной атмосфере.",
    CZ: "Pro rezervace a informace nás kontaktujte přes WhatsApp na výše uvedeném čísle. Rádi vás přivítáme v naší autentické horské atmosféře.",
    AL: "Për rezervimet dhe informacionet, ju lutem kontaktoni ne përmes WhatsApp-it në numrin e mësipërshme. Rado do t'ju pranojmë në atmosferën tonë të vetme të planinave.",
  },
  "footer.tagline": {
    IT: "Tradizione e sapori autentici della montagna",
    EN: "Authentic mountain traditions and flavors",
    DE: "Authentische Bergtraditionen und Aromen",
    BS: "Autentične planinske tradicije i okusi",
    RU: "Подлинные горные традиции и вкусы",
    CZ: "Autentické horské tradice a chutě",
    AL: "Tradicione dhe vlerat e vetme të planinave",
  },
  "footer.rights": {
    IT: "© 2024 La Busa del Sauc. Tutti i diritti riservati.",
    EN: "© 2024 La Busa del Sauc. All rights reserved.",
    DE: "© 2024 La Busa del Sauc. Alle Rechte vorbehalten.",
    BS: "© 2024 La Busa del Sauc. Sva prava pridržana.",
    RU: "© 2024 La Busa del Sauc. Все права защищены.",
    CZ: "© 2024 La Busa del Sauc. Všechna práva vyhrazena.",
    AL: "© 2024 La Busa del Sauc. tëra të drejtave të rezervuar.",
  },
  "hours.weekend": {
    IT: "Venerdì-Domenica: 10:00-22:00",
    EN: "Friday-Sunday: 10:00-22:00",
    DE: "Freitag-Sonntag: 10:00-22:00",
    BS: "Petak-Nedjelja: 10:00-22:00",
    RU: "Пятница-Воскресенье: 10:00-22:00",
    CZ: "Pátek-Neděle: 10:00-22:00",
    AL: "Vendres-Djekshëmbet: 10:00-22:00",
  },
  "hours.weekdays": {
    IT: "Lunedì-Giovedì: Chiuso",
    EN: "Monday-Thursday: Closed",
    DE: "Montag-Donnerstag: Geschlossen",
    BS: "Ponedjeljak-Četvrtak: Zatvoreno",
    RU: "Понедельник-Четверг: Закрыто",
    CZ: "Pondělí-Čtvrtek: Zavřeno",
    AL: "Hënë-Djuma: Mbyllur",
  },
  "whatsapp.info": {
    IT: "Per prenotazioni via WhatsApp",
    EN: "For WhatsApp reservations",
    DE: "Für WhatsApp-Reservierungen",
    BS: "Za rezervacije putem WhatsApp-a",
    RU: "Для бронирования через WhatsApp",
    CZ: "Pro rezervace přes WhatsApp",
    AL: "Për rezervimet përmes WhatsApp-it",
  },
  "menu.items.tagliere": {
    IT: "Tagliere di affettati misti con giardiniera",
    EN: "Mixed cold cuts platter with pickled vegetables",
    DE: "Gemischte Aufschnittplatte mit eingelegtem Gemüse",
    BS: "Mješovita ploča narezaka s ukiseljenim povrćem",
    RU: "Ассорти мясных деликатесов с маринованными овощами",
    CZ: "Míchané uzeniny s nakládanou zeleninou",
    AL: "Ploqë e mësivit të mështit me povrçë të ukisht",
  },
  "menu.items.formaggi": {
    IT: "Selezione di formaggi con mostarda ai fichi",
    EN: "Selection of cheeses with fig mustard",
    DE: "Käseauswahl mit Feigensenf",
    BS: "Izbor sireva s mostardom od smokava",
    RU: "Ассорти сыров с инжирной горчицей",
    CZ: "Výběr sýrů s fíkovou hořčicí",
    AL: "Përzgjedhje së sërumit me hořčicë të figave",
  },
  "menu.items.tartare": {
    IT: "Tartare tradizionale (senape, scalogno, capperi, olive, acciughe e worchester), insalatina invernale e i nostri crostini",
    EN: "Traditional tartare (mustard, shallot, capers, olives, anchovies and worcester), winter salad and our croutons",
    DE: "Traditionelles Tatar (Senf, Schalotten, Kapern, Oliven, Sardellen und Worcester), Wintersalat und unsere Croutons",
    BS: "Tradicionalni tartar (senf, ljutika, kapari, masline, inćuni i worcester), zimska salata i naši krostini",
    RU: "Традиционный тартар (горчица, лук-шалот, каперсы, оливки, анчоусы и вустер), зимний салат и наши гренки",
    CZ: "Tradiční tatarák (hořčice, šalotka, kapary, olivy, ančovičky a worcester), zimní salát a naše krutony",
    AL: "Tartare tradicional (mustardë, shallot, kaperi, ullinj, anchovi dhe worcester), sallatë dimërore dhe kroutonet tona",
  },
  "menu.items.flan": {
    IT: "Flan di zucca, fonduta di montasio, speck e spinacini",
    EN: "Pumpkin flan, montasio fondue, speck and baby spinach",
    DE: "Kürbisflan, Montasio-Fondue, Speck und Babyspinat",
    BS: "Flan od bundeve, montasio fondue, speck i baby špinat",
    RU: "Тыквенный флан, фондю из монтазио, спек и бэби-шпинат",
    CZ: "Dýňový flan, fondue z montasia, speck a baby špenát",
    AL: "Flan kungulli, fondue montasio, speck dhe spinaq i vogël",
  },
  "menu.items.pappardelle": {
    IT: "Pappardelle, ragù di cinghiale in rosso e fonduta di parmigiano",
    EN: "Pappardelle, wild boar ragù in red wine and parmesan fondue",
    DE: "Pappardelle, Wildschwein-Ragout in Rotwein und Parmesan-Fondue",
    BS: "Pappardelle, ragù od divlje svinje u crvenom vinu i parmezan fondue",
    RU: "Паппарделле, рагу из кабана в красном вине и фондю из пармезана",
    CZ: "Pappardelle, ragù z divočáka v červeném víně a parmezánové fondue",
    AL: "Pappardelle, ragù nga derri i egër në verë të kuqe dhe fondue parmigiano",
  },
  "menu.items.zuppa": {
    IT: "Zuppa del giorno",
    EN: "Soup of the day",
    DE: "Tagessuppe",
    BS: "Dnevna juha",
    RU: "Суп дня",
    CZ: "Denní polévka",
    AL: "Supë e ditës",
  },
  "menu.items.gnocchi": {
    IT: "Gnocchi fatti in casa ai porcini e salsiccia",
    EN: "Homemade gnocchi with porcini and sausage",
    DE: "Hausgemachte Gnocchi mit Steinpilzen und Wurst",
    BS: "Domaći njoki s vrganjima i kobasicom",
    RU: "Домашние ньокки с белыми грибами и колбасой",
    CZ: "Domácí gnocchi s hříbky a klobásou",
    AL: "Njoki të bërë në shtëpi me porcini dhe salsicë",
  },
  "menu.items.cervo": {
    IT: "Cervo* brasato con polenta",
    EN: "Braised venison* with polenta",
    DE: "Geschmorter Hirsch* mit Polenta",
    BS: "Dinstana srnetina* s polentom",
    RU: "Тушеная оленина* с полентой",
    CZ: "Dušená srnčí* s polentou",
    AL: "Cervo* brasato me polenta",
  },
  "menu.items.frico": {
    IT: "Frico con polenta",
    EN: "Frico with polenta",
    DE: "Frico mit Polenta",
    BS: "Frico s polentom",
    RU: "Фрико с полентой",
    CZ: "Frico s polentou",
    AL: "Frico me polenta",
  },
  "menu.items.tagliata": {
    IT: "Tagliata di manzo con contorno del giorno",
    EN: "Sliced beef with side dish of the day",
    DE: "Geschnittenes Rindfleisch mit Beilage des Tages",
    BS: "Narezana govedina s prilogom dana",
    RU: "Нарезанная говядина с гарниром дня",
    CZ: "Krájené hovězí s přílohou dne",
    AL: "Tagliata të lopës me guarnicion të ditës",
  },
  "menu.items.patate": {
    IT: "Patate fritte",
    EN: "French fries",
    DE: "Pommes frites",
    BS: "Pomfrit",
    RU: "Картофель фри",
    CZ: "Hranolky",
    AL: "Pomfrit",
  },
  "menu.items.funghi": {
    IT: "Funghi misti",
    EN: "Mixed mushrooms",
    DE: "Gemischte Pilze",
    BS: "Mješane gljive",
    RU: "Ассорти грибов",
    CZ: "Míchané houby",
    AL: "Mushrooms të mështit",
  },
  "menu.items.spinaci": {
    IT: "Spinaci stufati",
    EN: "Stewed spinach",
    DE: "Geschmorter Spinat",
    BS: "Dinstani špinat",
    RU: "Тушеный шпинат",
    CZ: "Dušený špenát",
    AL: "Spinaci të stufuara",
  },
  "menu.items.insalata": {
    IT: "Insalata mista",
    EN: "Mixed salad",
    DE: "Gemischter Salat",
    BS: "Mješana salata",
    RU: "Смешанный салат",
    CZ: "Míchený salát",
    AL: "Insalata të mështit",
  },
  "menu.items.spritz_aperol": {
    IT: "Spritz Aperol",
    EN: "Aperol Spritz",
    DE: "Aperol Spritz",
    BS: "Aperol Spritz",
    RU: "Аперол Шприц",
    CZ: "Aperol Spritz",
    AL: "Aperol Spritz",
  },
  "menu.items.spritz_campari": {
    IT: "Spritz Campari",
    EN: "Campari Spritz",
    DE: "Campari Spritz",
    BS: "Campari Spritz",
    RU: "Кампари Шприц",
    CZ: "Campari Spritz",
    AL: "Campari Spritz",
  },
  "menu.items.birra_egg": {
    IT: "Birra Eggenberger 0,25",
    EN: "Eggenberger Beer 0.25L",
    DE: "Eggenberger Bier 0,25L",
    BS: "Eggenberger pivo 0,25L",
    RU: "Пиво Эггенбергер 0,25л",
    CZ: "Eggenberger pivo 0,25L",
    AL: "Birra Eggenberger 0,25L",
  },
  "menu.items.birra_men": {
    IT: "Birra Menabrea 0,40",
    EN: "Menabrea Beer 0.40L",
    DE: "Menabrea Bier 0,40L",
    BS: "Menabrea pivo 0,40L",
    RU: "Пиво Менабреа 0,40л",
    CZ: "Menabrea pivo 0,40L",
    AL: "Birra Menabrea 0,40L",
  },
  "footer.createdBy": {
    IT: "Sito web creato da",
    EN: "Website created by",
    DE: "Website erstellt von",
    BS: "Web stranica kreirana od",
    RU: "Веб-сайт создан",
    CZ: "Webová stránka vytvořena",
    AL: "Faqja e internetit u krijua nga",
  },
  "footer.privacyPolicy": {
    IT: "Privacy Policy",
    EN: "Privacy Policy",
    DE: "Datenschutzrichtlinie",
    BS: "Pravila privatnosti",
    RU: "Политика конфиденциальности",
    CZ: "Zásady ochrany osobních údajů",
    AL: "Politika e privatitetit",
  },
  "footer.cookiePolicy": {
    IT: "Cookie Policy",
    EN: "Cookie Policy",
    DE: "Cookie-Richtlinie",
    BS: "Pravila kolačića",
    RU: "Политика использования файлов cookie",
    CZ: "Zásady používání souborů cookie",
    AL: "Politika e kolaçeve",
  },
  "privacy.title": {
    IT: "Informativa sulla Privacy",
    EN: "Privacy Policy",
    DE: "Datenschutzerklärung",
    BS: "Pravila privatnosti",
    RU: "Политика конфиденциальности",
    CZ: "Zásady ochrany osobních údajů",
    AL: "Politika e privatitetit",
  },
  "privacy.content": {
    IT: "Questo sito web non raccoglie dati personali degli utenti. Utilizziamo solo cookie tecnici necessari per il funzionamento del sito.",
    EN: "This website does not collect personal user data. We only use technical cookies necessary for the site's functionality.",
    DE: "Diese Website sammelt keine persönlichen Benutzerdaten. Wir verwenden nur technische Cookies, die für die Funktionalität der Website erforderlich sind.",
    BS: "Ova web stranica ne prikuplja osobne podatke korisnika. Koristimo samo tehničke kolačiće potrebne za funkcioniranje stranice.",
    RU: "Этот веб-сайт не собирает персональные данные пользователей. Мы используем только технические файлы cookie, необходимые для функционирования сайта.",
    CZ: "Tato webová stránka neshromažďuje osobní údaje uživatelů. Používáme pouze technické soubory cookie nezbytné pro fungování stránky.",
    AL: "Kjo faqe web nuk kolekcionon të dhëna personale të përdoruesve. Përdorim vetëm cookie të teknikësh të nevojshme për funksionimin e faqes.",
  },
  "cookie.title": {
    IT: "Informativa sui Cookie",
    EN: "Cookie Policy",
    DE: "Cookie-Richtlinie",
    BS: "Pravila kolačića",
    RU: "Политика использования файлов cookie",
    CZ: "Zásady používání souborů cookie",
    AL: "Politika e kolaçeve",
  },
  "cookie.content": {
    IT: "Utilizziamo solo cookie tecnici essenziali per il funzionamento del sito. Non utilizziamo cookie di tracciamento o di profilazione.",
    EN: "We only use essential technical cookies for the site's functionality. We do not use tracking or profiling cookies.",
    DE: "Wir verwenden nur wesentliche technische Cookies für die Funktionalität der Website. Wir verwenden keine Tracking- oder Profiling-Cookies.",
    BS: "Koristimo samo osnovne tehničke kolačiće za funkcioniranje stranice. Ne koristimo kolačiće za praćenje ili profiliranje.",
    RU: "Мы используем только основные технические файлы cookie для функционирования сайта. Мы не используем файлы cookie для отслеживания или профилирования.",
    CZ: "Používáme pouze základní technické soubory cookie pro fungování stránky. Nepoužíváme sledovací nebo profilovací soubory cookie.",
    AL: "Përdorim vetëm cookie të teknikësh të oshtinë për funksionimin e faqes. S'përdorim cookie për shqyrtimin ose profilimin.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("IT")

  const t = (key: string): string => {
    return translations[key as keyof typeof translations]?.[language] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { languages }
