"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "IT" | "EN" | "FR" | "DE" | "ES" | "PT" | "RU" | "AR" | "ZH" | "JA"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string | string[]
}

const languages = {
  IT: { flag: "🇮🇹", name: "Italiano" },
  EN: { flag: "🇬🇧", name: "English" },
  FR: { flag: "🇫🇷", name: "Français" },
  DE: { flag: "🇩🇪", name: "Deutsch" },
  ES: { flag: "🇪🇸", name: "Español" },
  PT: { flag: "🇵🇹", name: "Português" },
  RU: { flag: "🇷🇺", name: "Русский" },
  AR: { flag: "🇸🇦", name: "العربية" },
  ZH: { flag: "🇨🇳", name: "中文" },
  JA: { flag: "🇯🇵", name: "日本語" },
}

const translations = {
  // Navigation
  "nav.stock": {
    IT: "Stock",
    EN: "Stock",
    FR: "Stock",
    DE: "Bestand",
    ES: "Stock",
    PT: "Stock",
    RU: "Склад",
    AR: "المخزون",
    ZH: "库存",
    JA: "在庫",
  },
  "nav.auctions": {
    IT: "Aste",
    EN: "Auctions",
    FR: "Enchères",
    DE: "Auktionen",
    ES: "Subastas",
    PT: "Leilões",
    RU: "Аукционы",
    AR: "المزادات",
    ZH: "拍卖",
    JA: "オークション",
  },
  "nav.invest": {
    IT: "Investi",
    EN: "Invest",
    FR: "Investir",
    DE: "Investieren",
    ES: "Invertir",
    PT: "Investir",
    RU: "Инвестировать",
    AR: "استثمر",
    ZH: "投资",
    JA: "投資",
  },
  "nav.sell": {
    IT: "Vendi",
    EN: "Sell",
    FR: "Vendre",
    DE: "Verkaufen",
    ES: "Vender",
    PT: "Vender",
    RU: "Продать",
    AR: "بيع",
    ZH: "出售",
    JA: "売る",
  },
  "nav.services": {
    IT: "Servizi",
    EN: "Services",
    FR: "Services",
    DE: "Dienstleistungen",
    ES: "Servicios",
    PT: "Serviços",
    RU: "Услуги",
    AR: "الخدمات",
    ZH: "服务",
    JA: "サービス",
  },
  "nav.insights": {
    IT: "Approfondimenti",
    EN: "Insights",
    FR: "Analyses",
    DE: "Einblicke",
    ES: "Perspectivas",
    PT: "Insights",
    RU: "Аналитика",
    AR: "رؤى",
    ZH: "洞察",
    JA: "インサイト",
  },
  "nav.faq": {
    IT: "FAQ",
    EN: "FAQ",
    FR: "FAQ",
    DE: "FAQ",
    ES: "FAQ",
    PT: "FAQ",
    RU: "FAQ",
    AR: "الأسئلة الشائعة",
    ZH: "常见问题",
    JA: "よくある質問",
  },
  "nav.contact": {
    IT: "Contatti",
    EN: "Contact",
    FR: "Contact",
    DE: "Kontakt",
    ES: "Contacto",
    PT: "Contato",
    RU: "Контакты",
    AR: "اتصل",
    ZH: "联系",
    JA: "お問い合わせ",
  },
  "nav.register": {
    IT: "Registrati",
    EN: "Register",
    FR: "S'inscrire",
    DE: "Registrieren",
    ES: "Registrarse",
    PT: "Registrar",
    RU: "Регистрация",
    AR: "تسجيل",
    ZH: "注册",
    JA: "登録",
  },

  // Hero
  "hero.title": {
    IT: "Broker Motors",
    EN: "Broker Motors",
    FR: "Broker Motors",
    DE: "Broker Motors",
    ES: "Broker Motors",
    PT: "Broker Motors",
    RU: "Broker Motors",
    AR: "بروكر موتورز",
    ZH: "经纪汽车",
    JA: "ブローカーモーターズ",
  },
  "hero.subtitle": {
    IT: "Investi nelle supercar, guadagna ogni mese",
    EN: "Invest in Supercars, Earn Monthly Income",
    FR: "Investissez dans les supercars, gagnez chaque mois",
    DE: "Investieren Sie in Supercars, verdienen Sie monatlich",
    ES: "Invierte en supercoches, gana cada mes",
    PT: "Invista em supercarros, ganhe mensalmente",
    RU: "Инвестируйте в суперкары, зарабатывайте ежемесячно",
    AR: "استثمر في السيارات الفائقة، اكسب شهرياً",
    ZH: "投资超级跑车，每月赚取收益",
    JA: "スーパーカーに投資し、毎月収益を得る",
  },
  "hero.ctaInvest": {
    IT: "Inizia a investire",
    EN: "Start Investing",
    FR: "Commencer à investir",
    DE: "Investieren beginnen",
    ES: "Empezar a invertir",
    PT: "Começar a investir",
    RU: "Начать инвестировать",
    AR: "ابدأ الاستثمار",
    ZH: "开始投资",
    JA: "投資を始める",
  },
  "hero.ctaAuctions": {
    IT: "Scopri le aste in corso",
    EN: "Explore Live Auctions",
    FR: "Découvrir les enchères en cours",
    DE: "Live-Auktionen entdecken",
    ES: "Explorar subastas en vivo",
    PT: "Explorar leilões ao vivo",
    RU: "Исследовать живые аукционы",
    AR: "استكشف المزادات المباشرة",
    ZH: "探索现场拍卖",
    JA: "ライブオークションを探索",
  },

  // Stock
  "stock.title": {
    IT: "Auto in evidenza",
    EN: "Featured Cars",
    FR: "Voitures en vedette",
    DE: "Ausgewählte Autos",
    ES: "Coches destacados",
    PT: "Carros em destaque",
    RU: "Рекомендуемые автомобили",
    AR: "السيارات المميزة",
    ZH: "精选汽车",
    JA: "注目の車",
  },

  // Badges
  "badges.live": {
    IT: "LIVE",
    EN: "LIVE",
    FR: "EN DIRECT",
    DE: "LIVE",
    ES: "EN VIVO",
    PT: "AO VIVO",
    RU: "ПРЯМОЙ ЭФИР",
    AR: "مباشر",
    ZH: "直播",
    JA: "ライブ",
  },
  "badges.noReserve": {
    IT: "NO RESERVE",
    EN: "NO RESERVE",
    FR: "SANS RÉSERVE",
    DE: "OHNE MINDESTGEBOT",
    ES: "SIN RESERVA",
    PT: "SEM RESERVA",
    RU: "БЕЗ РЕЗЕРВА",
    AR: "بدون احتياطي",
    ZH: "无底价",
    JA: "ノーリザーブ",
  },
  "badges.soon": {
    IT: "PRESTO",
    EN: "COMING SOON",
    FR: "BIENTÔT",
    DE: "DEMNÄCHST",
    ES: "PRÓXIMAMENTE",
    PT: "EM BREVE",
    RU: "СКОРО",
    AR: "قريباً",
    ZH: "即将推出",
    JA: "近日公開",
  },

  // USP
  "usp.title": {
    IT: "Perché investire con Broker Motors?",
    EN: "Why invest with Broker Motors?",
    FR: "Pourquoi investir avec Broker Motors?",
    DE: "Warum mit Broker Motors investieren?",
    ES: "¿Por qué invertir con Broker Motors?",
    PT: "Por que investir com Broker Motors?",
    RU: "Почему инвестировать с Broker Motors?",
    AR: "لماذا تستثمر مع بروكر موتورز؟",
    ZH: "为什么选择经纪汽车投资？",
    JA: "なぜブローカーモーターズで投資するのか？",
  },
  "usp.p1": {
    IT: "Accesso esclusivo al mercato delle supercar",
    EN: "Exclusive access to the supercar market",
    FR: "Accès exclusif au marché des supercars",
    DE: "Exklusiver Zugang zum Supercar-Markt",
    ES: "Acceso exclusivo al mercado de supercoches",
    PT: "Acesso exclusivo ao mercado de supercarros",
    RU: "Эксклюзивный доступ к рынку суперкаров",
    AR: "وصول حصري لسوق السيارات الفائقة",
    ZH: "独家进入超级跑车市场",
    JA: "スーパーカー市場への独占アクセス",
  },
  "usp.p2": {
    IT: "Investimenti frazionati accessibili",
    EN: "Fractional investments accessible to everyone",
    FR: "Investissements fractionnés accessibles",
    DE: "Zugängliche Teilinvestitionen",
    ES: "Inversiones fraccionadas accesibles",
    PT: "Investimentos fracionados acessíveis",
    RU: "Доступные дробные инвестиции",
    AR: "استثمارات جزئية متاحة",
    ZH: "人人可及的分数投资",
    JA: "誰でもアクセス可能な分割投資",
  },
  "usp.p3": {
    IT: "Rendite mensili garantite e trasparenti",
    EN: "Guaranteed and transparent monthly returns",
    FR: "Rendements mensuels garantis et transparents",
    DE: "Garantierte und transparente monatliche Renditen",
    ES: "Rendimientos mensuales garantizados y transparentes",
    PT: "Retornos mensais garantidos e transparentes",
    RU: "Гарантированная и прозрачная ежемесячная доходность",
    AR: "عوائد شهرية مضمونة وشفافة",
    ZH: "保证透明的月度回报",
    JA: "保証された透明な月次リターン",
  },
  "usp.p4": {
    IT: "Gestione completa dei nostri esperti",
    EN: "Full management by our experts",
    FR: "Gestion complète par nos experts",
    DE: "Vollständige Verwaltung durch unsere Experten",
    ES: "Gestión completa por nuestros expertos",
    PT: "Gestão completa pelos nossos especialistas",
    RU: "Полное управление нашими экспертами",
    AR: "إدارة كاملة من قبل خبرائنا",
    ZH: "我们专家的全面管理",
    JA: "専門家による完全管理",
  },

  // Investment
  "invest.title": {
    IT: "Come funziona l'investimento in supercar",
    EN: "How Supercar Investment Works",
    FR: "Comment fonctionne l'investissement en supercars",
    DE: "Wie Supercar-Investitionen funktionieren",
    ES: "Cómo funciona la inversión en supercoches",
    PT: "Como funciona o investimento em supercarros",
    RU: "Как работают инвестиции в суперкары",
    AR: "كيف يعمل الاستثمار في السيارات الفائقة",
    ZH: "超级跑车投资如何运作",
    JA: "スーパーカー投資の仕組み",
  },
  "invest.s1": {
    IT: "Seleziona la quota",
    EN: "Choose your share",
    FR: "Choisissez votre part",
    DE: "Wählen Sie Ihren Anteil",
    ES: "Elige tu participación",
    PT: "Escolha sua cota",
    RU: "Выберите свою долю",
    AR: "اختر حصتك",
    ZH: "选择您的份额",
    JA: "シェアを選択",
  },
  "invest.s2": {
    IT: "Firma digitale",
    EN: "Sign digitally",
    FR: "Signature numérique",
    DE: "Digital signieren",
    ES: "Firma digital",
    PT: "Assine digitalmente",
    RU: "Цифровая подпись",
    AR: "التوقيع الرقمي",
    ZH: "数字签名",
    JA: "デジタル署名",
  },
  "invest.s3": {
    IT: "Ricevi rendite mensili",
    EN: "Receive monthly income",
    FR: "Recevez des revenus mensuels",
    DE: "Monatliche Erträge erhalten",
    ES: "Recibe ingresos mensuales",
    PT: "Receba renda mensal",
    RU: "Получайте ежемесячный доход",
    AR: "احصل على دخل شهري",
    ZH: "获得月收入",
    JA: "月収入を受け取る",
  },
  "invest.cta": {
    IT: "Calcola il tuo rendimento",
    EN: "Get your free return estimate",
    FR: "Calculez votre rendement",
    DE: "Berechnen Sie Ihre Rendite",
    ES: "Calcula tu rendimiento",
    PT: "Calcule seu retorno",
    RU: "Рассчитайте свою доходность",
    AR: "احسب عائدك",
    ZH: "计算您的回报",
    JA: "リターンを計算",
  },

  // Sell
  "sell.title": {
    IT: "Vendi la tua auto con Broker Motors",
    EN: "Sell your car with Broker Motors",
    FR: "Vendez votre voiture avec Broker Motors",
    DE: "Verkaufen Sie Ihr Auto mit Broker Motors",
    ES: "Vende tu coche con Broker Motors",
    PT: "Venda seu carro com Broker Motors",
    RU: "Продайте свой автомобиль с Broker Motors",
    AR: "بع سيارتك مع بروكر موتورز",
    ZH: "通过经纪汽车出售您的汽车",
    JA: "ブローカーモーターズで車を売る",
  },
  "sell.stepsTitle": {
    IT: "Processo in 3 step",
    EN: "Simple 3-step process",
    FR: "Processus simple en 3 étapes",
    DE: "Einfacher 3-Schritte-Prozess",
    ES: "Proceso simple de 3 pasos",
    PT: "Processo simples de 3 etapas",
    RU: "Простой 3-шаговый процесс",
    AR: "عملية بسيطة من 3 خطوات",
    ZH: "简单的3步流程",
    JA: "シンプルな3ステップ",
  },
  "sell.s1": {
    IT: "Inserisci dettagli",
    EN: "Submit details",
    FR: "Soumettez les détails",
    DE: "Details einreichen",
    ES: "Envía detalles",
    PT: "Envie detalhes",
    RU: "Отправить детали",
    AR: "أرسل التفاصيل",
    ZH: "提交详情",
    JA: "詳細を送信",
  },
  "sell.s2": {
    IT: "Valutazione esperti",
    EN: "Expert assessment",
    FR: "Évaluation d'experts",
    DE: "Expertenbewertung",
    ES: "Evaluación de expertos",
    PT: "Avaliação de especialistas",
    RU: "Экспертная оценка",
    AR: "تقييم الخبراء",
    ZH: "专家评估",
    JA: "専門家による評価",
  },
  "sell.s3": {
    IT: "Vai all'asta",
    EN: "Go live at auction",
    FR: "Mise aux enchères",
    DE: "Live zur Auktion",
    ES: "Ir a subasta en vivo",
    PT: "Ir ao leilão ao vivo",
    RU: "Выйти на аукцион",
    AR: "انتقل للمزاد المباشر",
    ZH: "进入现场拍卖",
    JA: "ライブオークションへ",
  },

  // Form
  "sell.form.name": {
    IT: "Nome e cognome",
    EN: "Full name",
    FR: "Nom complet",
    DE: "Vollständiger Name",
    ES: "Nombre completo",
    PT: "Nome completo",
    RU: "Полное имя",
    AR: "الاسم الكامل",
    ZH: "全名",
    JA: "フルネーム",
  },
  "sell.form.email": {
    IT: "Email",
    EN: "Email",
    FR: "Email",
    DE: "E-Mail",
    ES: "Email",
    PT: "Email",
    RU: "Электронная почта",
    AR: "البريد الإلكتروني",
    ZH: "电子邮件",
    JA: "メール",
  },
  "sell.form.phone": {
    IT: "Telefono",
    EN: "Phone",
    FR: "Téléphone",
    DE: "Telefon",
    ES: "Teléfono",
    PT: "Telefone",
    RU: "Телефон",
    AR: "الهاتف",
    ZH: "电话",
    JA: "電話",
  },
  "sell.form.car": {
    IT: "Modello",
    EN: "Model",
    FR: "Modèle",
    DE: "Modell",
    ES: "Modelo",
    PT: "Modelo",
    RU: "Модель",
    AR: "الطراز",
    ZH: "型号",
    JA: "モデル",
  },
  "sell.form.km": {
    IT: "Chilometraggio",
    EN: "Mileage",
    FR: "Kilométrage",
    DE: "Kilometerstand",
    ES: "Kilometraje",
    PT: "Quilometragem",
    RU: "Пробег",
    AR: "المسافة المقطوعة",
    ZH: "里程",
    JA: "走行距離",
  },
  "sell.form.year": {
    IT: "Anno",
    EN: "Year",
    FR: "Année",
    DE: "Jahr",
    ES: "Año",
    PT: "Ano",
    RU: "Год",
    AR: "السنة",
    ZH: "年份",
    JA: "年",
  },
  "sell.form.submit": {
    IT: "Richiedi valutazione gratuita",
    EN: "Get free valuation",
    FR: "Demander une évaluation gratuite",
    DE: "Kostenlose Bewertung anfordern",
    ES: "Solicitar valoración gratuita",
    PT: "Solicitar avaliação gratuita",
    RU: "Получить бесплатную оценку",
    AR: "احصل على تقييم مجاني",
    ZH: "获取免费评估",
    JA: "無料査定を依頼",
  },

  // Insights
  "insights.title": {
    IT: "Approfondimenti",
    EN: "Insights",
    FR: "Analyses",
    DE: "Einblicke",
    ES: "Perspectivas",
    PT: "Insights",
    RU: "Аналитика",
    AR: "رؤى",
    ZH: "洞察",
    JA: "インサイト",
  },
  "insights.a1": {
    IT: "Tendenze mercato auto di lusso 2025",
    EN: "Luxury Car Market Trends 2025",
    FR: "Tendances du marché des voitures de luxe 2025",
    DE: "Luxusauto-Markttrends 2025",
    ES: "Tendencias del mercado de coches de lujo 2025",
    PT: "Tendências do mercado de carros de luxo 2025",
    RU: "Тенденции рынка роскошных автомобилей 2025",
    AR: "اتجاهات سوق السيارات الفاخرة 2025",
    ZH: "2025年豪华汽车市场趋势",
    JA: "2025年高級車市場のトレンド",
  },
  "insights.a2": {
    IT: "Guida aste: come partecipare con successo",
    EN: "Bidding Guide: How to Win",
    FR: "Guide des enchères: comment gagner",
    DE: "Bietleitfaden: Wie man gewinnt",
    ES: "Guía de pujas: cómo ganar",
    PT: "Guia de lances: como vencer",
    RU: "Руководство по торгам: как выиграть",
    AR: "دليل المزايدة: كيفية الفوز",
    ZH: "竞拍指南：如何获胜",
    JA: "入札ガイド：勝つ方法",
  },
  "insights.a3": {
    IT: "Import/Export: IVA e dazi in EU/UK",
    EN: "EU/UK VAT & Import Duties Guide",
    FR: "Guide TVA et droits d'importation UE/UK",
    DE: "EU/UK MwSt. & Importzölle Leitfaden",
    ES: "Guía de IVA y aranceles de importación UE/UK",
    PT: "Guia de IVA e taxas de importação UE/UK",
    RU: "Руководство по НДС и импортным пошлинам ЕС/Великобритания",
    AR: "دليل ضريبة القيمة المضافة ورسوم الاستيراد في الاتحاد الأوروبي/المملكة المتحدة",
    ZH: "欧盟/英国增值税和进口关税指南",
    JA: "EU/UK付加価値税・輸入関税ガイド",
  },

  // FAQ
  "faq.title": {
    IT: "Domande frequenti",
    EN: "Frequently Asked Questions",
    FR: "Questions fréquemment posées",
    DE: "Häufig gestellte Fragen",
    ES: "Preguntas frecuentes",
    PT: "Perguntas frequentes",
    RU: "Часто задаваемые вопросы",
    AR: "الأسئلة الشائعة",
    ZH: "常见问题",
    JA: "よくある質問",
  },
  "faq.q1": {
    IT: "Quali sono le commissioni?",
    EN: "What are the commission rates?",
    FR: "Quels sont les taux de commission?",
    DE: "Wie hoch sind die Provisionen?",
    ES: "¿Cuáles son las tasas de comisión?",
    PT: "Quais são as taxas de comissão?",
    RU: "Какие комиссионные ставки?",
    AR: "ما هي معدلات العمولة؟",
    ZH: "佣金费率是多少？",
    JA: "手数料率はいくらですか？",
  },
  "faq.q2": {
    IT: "Come funziona il deposito cauzionale?",
    EN: "How does the security deposit work?",
    FR: "Comment fonctionne le dépôt de garantie?",
    DE: "Wie funktioniert die Kaution?",
    ES: "¿Cómo funciona el depósito de seguridad?",
    PT: "Como funciona o depósito de segurança?",
    RU: "Как работает залог?",
    AR: "كيف يعمل الإيداع الضماني؟",
    ZH: "保证金如何运作？",
    JA: "保証金はどのように機能しますか？",
  },
  "faq.q3": {
    IT: "Come avvengono i pagamenti?",
    EN: "How do payments work?",
    FR: "Comment fonctionnent les paiements?",
    DE: "Wie funktionieren die Zahlungen?",
    ES: "¿Cómo funcionan los pagos?",
    PT: "Como funcionam os pagamentos?",
    RU: "Как работают платежи?",
    AR: "كيف تعمل المدفوعات؟",
    ZH: "付款如何运作？",
    JA: "支払いはどのように機能しますか？",
  },

  // Final CTA
  "ctaFinal.title": {
    IT: "Unisciti a migliaia di investitori e collezionisti che hanno scelto Broker Motors",
    EN: "Join thousands of investors and collectors who chose Broker Motors",
    FR: "Rejoignez des milliers d'investisseurs et collectionneurs qui ont choisi Broker Motors",
    DE: "Schließen Sie sich Tausenden von Investoren und Sammlern an, die Broker Motors gewählt haben",
    ES: "Únete a miles de inversores y coleccionistas que eligieron Broker Motors",
    PT: "Junte-se a milhares de investidores e colecionadores que escolheram Broker Motors",
    RU: "Присоединяйтесь к тысячам инвесторов и коллекционеров, выбравших Broker Motors",
    AR: "انضم إلى آلاف المستثمرين والجامعين الذين اختاروا بروكر موتورز",
    ZH: "加入选择经纪汽车的数千名投资者和收藏家",
    JA: "ブローカーモーターズを選んだ数千人の投資家とコレクターに参加",
  },
  "ctaFinal.cta1": {
    IT: "Scopri le aste",
    EN: "Explore Auctions",
    FR: "Découvrir les enchères",
    DE: "Auktionen entdecken",
    ES: "Explorar subastas",
    PT: "Explorar leilões",
    RU: "Исследовать аукционы",
    AR: "استكشف المزادات",
    ZH: "探索拍卖",
    JA: "オークションを探索",
  },
  "ctaFinal.cta2": {
    IT: "Iscriviti ora",
    EN: "Register Now",
    FR: "S'inscrire maintenant",
    DE: "Jetzt registrieren",
    ES: "Registrarse ahora",
    PT: "Registrar agora",
    RU: "Зарегистрироваться сейчас",
    AR: "سجل الآن",
    ZH: "立即注册",
    JA: "今すぐ登録",
  },

  // Footer
  "footer.tagline": {
    IT: "La piattaforma leader per aste e investimenti in auto di lusso. Selezione curata, trasparenza totale, pagamenti sicuri.",
    EN: "The leading platform for luxury car auctions and investments. Curated selection, full transparency, secure payments.",
    FR: "La plateforme leader pour les enchères et investissements en voitures de luxe. Sélection soignée, transparence totale, paiements sécurisés.",
    DE: "Die führende Plattform für Luxusauto-Auktionen und Investitionen. Kuratierte Auswahl, vollständige Transparenz, sichere Zahlungen.",
    ES: "La plataforma líder para subastas e inversiones en coches de lujo. Selección curada, transparencia total, pagos seguros.",
    PT: "A plataforma líder para leilões e investimentos em carros de luxo. Seleção curada, transparência total, pagamentos seguros.",
    RU: "Ведущая платформа для аукционов и инвестиций в роскошные автомобили. Кураторский отбор, полная прозрачность, безопасные платежи.",
    AR: "المنصة الرائدة لمزادات واستثمارات السيارات الفاخرة. اختيار منسق، شفافية كاملة، مدفوعات آمنة.",
    ZH: "豪华汽车拍卖和投资的领先平台。精选车辆，完全透明，安全支付。",
    JA: "高級車オークションと投資の主要プラットフォーム。厳選された選択、完全な透明性、安全な支払い。",
  },
  "footer.legal": {
    IT: "Note legali",
    EN: "Legal",
    FR: "Mentions légales",
    DE: "Rechtliches",
    ES: "Legal",
    PT: "Legal",
    RU: "Правовая информация",
    AR: "قانوني",
    ZH: "法律",
    JA: "法的事項",
  },
  "footer.privacy": {
    IT: "Privacy Policy",
    EN: "Privacy Policy",
    FR: "Politique de confidentialité",
    DE: "Datenschutzrichtlinie",
    ES: "Política de privacidad",
    PT: "Política de privacidade",
    RU: "Политика конфиденциальности",
    AR: "سياسة الخصوصية",
    ZH: "隐私政策",
    JA: "プライバシーポリシー",
  },
  "footer.cookies": {
    IT: "Cookie Policy",
    EN: "Cookie Policy",
    FR: "Politique des cookies",
    DE: "Cookie-Richtlinie",
    ES: "Política de cookies",
    PT: "Política de cookies",
    RU: "Политика файлов cookie",
    AR: "سياسة ملفات تعريف الارتباط",
    ZH: "Cookie政策",
    JA: "Cookieポリシー",
  },
  "footer.terms": {
    IT: "Termini & Condizioni",
    EN: "Terms & Conditions",
    FR: "Conditions générales",
    DE: "Geschäftsbedingungen",
    ES: "Términos y condiciones",
    PT: "Termos e condições",
    RU: "Условия использования",
    AR: "الشروط والأحكام",
    ZH: "条款和条件",
    JA: "利用規約",
  },
  "footer.complaints": {
    IT: "Procedura reclami",
    EN: "Complaints Procedure",
    FR: "Procédure de réclamation",
    DE: "Beschwerdeverfahren",
    ES: "Procedimiento de quejas",
    PT: "Procedimento de reclamações",
    RU: "Процедура жалоб",
    AR: "إجراءات الشكاوى",
    ZH: "投诉程序",
    JA: "苦情処理手続き",
  },
  "footer.contact": {
    IT: "Contatti",
    EN: "Contact",
    FR: "Contact",
    DE: "Kontakt",
    ES: "Contacto",
    PT: "Contato",
    RU: "Контакты",
    AR: "اتصل",
    ZH: "联系",
    JA: "お問い合わせ",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("IT")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("broker-motors-lang") as Language
    if (savedLanguage && languages[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("broker-motors-lang", lang)
  }

  const t = (key: string): string | string[] => {
    const translation = translations[key as keyof typeof translations]
    if (!translation) return key

    return translation[language] || translation["IT"] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { languages }
