"use client"

import type React from "react"

import { createContext, useContext, useState } from "react"

type Language = "IT" | "EN" | "DE" | "BS" | "RU" | "CZ" | "AL"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const languages = {
  IT: { flag: "🇮🇹", name: "Italiano" },
  EN: { flag: "🇬🇧", name: "English" },
  DE: { flag: "🇩🇪", name: "Deutsch" },
  BS: { flag: "🇧🇦", name: "Bosanski" },
  RU: { flag: "🇷🇺", name: "Русский" },
  CZ: { flag: "🇨🇿", name: "Čeština" },
  AL: { flag: "🇦🇱", name: "Shqip" },
}

const translations = {
  "nav.home": { IT: "Home", EN: "Home", DE: "Startseite", BS: "Početna", RU: "Главная", CZ: "Domů", AL: "Kryefaqja" },
  "nav.about": {
    IT: "Chi Siamo",
    EN: "About Us",
    DE: "Über uns",
    BS: "O nama",
    RU: "О нас",
    CZ: "O nás",
    AL: "Rreth nesh",
  },
  "nav.menu": { IT: "Menu", EN: "Menu", DE: "Speisekarte", BS: "Meni", RU: "Меню", CZ: "Menu", AL: "Menyja" },
  "nav.gallery": {
    IT: "Galleria",
    EN: "Gallery",
    DE: "Galerie",
    BS: "Galerija",
    RU: "Галерея",
    CZ: "Galerie",
    AL: "Galeria",
  },
  "nav.contact": {
    IT: "Contatti",
    EN: "Contact",
    DE: "Kontakt",
    BS: "Kontakt",
    RU: "Контакты",
    CZ: "Kontakt",
    AL: "Kontakti",
  },

  "hero.welcome": {
    IT: "BENVENUTI PRESSO",
    EN: "WELCOME TO",
    DE: "WILLKOMMEN BEI",
    BS: "DOBRODOŠLI U",
    RU: "ДОБРО ПОЖАЛОВАТЬ В",
    CZ: "VÍTEJTE V",
    AL: "MIRË SE VINI NË",
  },
  "hero.subtitle": {
    IT: "Un locale rinnovato che vi accoglie con calore e vi coccola con i sapori del territorio, per trasformare ogni momento di relax in un piacere autentico.",
    EN: "A renovated venue ready to welcome and pamper you in a warm and welcoming atmosphere, accompanying you with a selection of local products to make your moments of relaxation comfortable.",
    DE: "Ein renoviertes Lokal, bereit Sie in warmer und einladender Atmosphäre zu empfangen und zu verwöhnen, begleitet von einer Auswahl regionaler Produkte für entspannte Momente.",
    BS: "Obnovljeni lokal spreman da vas dočeka i mazi u toploj i gostoljubivoj atmosferi, prateći vas izborom lokalnih proizvoda za ugodne trenutke opuštanja.",
    RU: "Обновленное заведение готово принять и побаловать вас в теплой и гостеприимной атмосфере, предлагая отборные местные продукты для комфортного отдыха.",
    CZ: "Zrekonstruovaný podnik připravený vás uvítat a rozmazlovat v teplé a příjemné atmosféře, doprovázet vás výběrem místních produktů pro pohodlné chvíle odpočinku.",
    AL: "Një lokal i rinovuar i gatshëm t'ju presë dhe t'ju përkëdhelë në një atmosferë të ngrohtë dhe mikpritëse, duke ju shoqëruar me një përzgjedhje produktesh lokale për t'i bërë momentet tuaja të relaksit komode.",
  },
  "hero.discover": {
    IT: "Scopri di Più",
    EN: "Discover More",
    DE: "Mehr entdecken",
    BS: "Otkrijte više",
    RU: "Узнать больше",
    CZ: "Objevte více",
    AL: "Zbuloni më shumë",
  },

  "about.title": {
    IT: "La Nostra Storia",
    EN: "Our Story",
    DE: "Unsere Geschichte",
    BS: "Naša priča",
    RU: "Наша история",
    CZ: "Náš příběh",
    AL: "Historia jonë",
  },
  "about.description": {
    IT: "Immerso nella bellezza delle montagne, La Busa del Sauc rappresenta l'essenza della tradizione culinaria locale. Ogni piatto racconta una storia, ogni sapore evoca ricordi di antiche ricette tramandate di generazione in generazione.",
    EN: "Immersed in the beauty of the mountains, La Busa del Sauc represents the essence of local culinary tradition. Every dish tells a story, every flavor evokes memories of ancient recipes passed down from generation to generation.",
    DE: "Eingebettet in die Schönheit der Berge repräsentiert La Busa del Sauc die Essenz der lokalen kulinarischen Tradition. Jedes Gericht erzählt eine Geschichte, jeder Geschmack weckt Erinnerungen an alte Rezepte, die von Generation zu Generation weitergegeben wurden.",
    BS: "Ubiveni u ljepotu planina, La Busa del Sauc predstavlja osnovu lokalne kulinarske tradicije. Svako jelo priča priču, svaki okus podigne sjećanje na drevne recepte prenošene od generacije na generaciju.",
    RU: "Погруженный в красоту гор, La Busa del Sauc представляет суть местной кулинарной традиции. Каждое блюдо рассказывает историю, каждый вкус вызывает воспоминания о древних рецептах, передаваемых из поколения в поколение.",
    CZ: "Ponořen do krásy hor, La Busa del Sauc představuje podstatu místní kulinářské tradice. Každé jídlo vypráví příběh, každá chuť vyvolává vzpomínky na staré recepty předávané z generace na generaci.",
    AL: "Përshëndetetje nëpër ljeposinë e planinave, La Busa del Sauc përshkruan oshtinë e tradicioneve kulinare të vendit. Çdo jelo dëshiron një histori, çdo flasë kërkon sjeçtje për receptet tradicionale të vjetër të pasur nga një generacion në tjetrin.",
  },
  "atmosphere.title": {
    IT: "Atmosfera Accogliente",
    EN: "Welcoming Atmosphere",
    DE: "Einladende Atmosphäre",
    BS: "Ugodna atmosfera",
    RU: "Уютная атмосфера",
    CZ: "Příjemná atmosféra",
    AL: "Atmosferë mikpritëse",
  },
  "atmosphere.description1": {
    IT: "Il nostro locale rinnovato mantiene il calore e l'autenticità della tradizione montana, offrendo un ambiente dove ogni ospite si sente a casa. L'arredamento in legno naturale e i dettagli curati creano l'atmosfera perfetta per momenti indimenticabili.",
    EN: "Our renovated venue maintains the warmth and authenticity of mountain tradition, offering an environment where every guest feels at home. Natural wood furnishings and carefully crafted details create the perfect atmosphere for unforgettable moments.",
    DE: "Unser renoviertes Lokal bewahrt die Wärme und Authentizität der Bergtradition und bietet eine Umgebung, in der sich jeder Gast wie zu Hause fühlt. Natürliche Holzmöbel und sorgfältig gestaltete Details schaffen die perfekte Atmosphäre für unvergessliche Momente.",
    BS: "Naš obnovljeni lokal zadržava toplinu i autentičnost planinske tradicije, nudeći okruženje u kojem se svaki gost osjeća kao kod kuće. Prirodni drveni namještaj i pažljivo osmišljeni detalji stvaraju savršenu atmosferu za nezaboravne trenutke.",
    RU: "Наше обновленное заведение сохраняет тепло и подлинность горных традиций, предлагая среду, где каждый гость чувствует себя как дома. Натуральная деревянная мебель и тщательно продуманные детали создают идеальную атмосферу для незабываемых моментов.",
    CZ: "Náš zrekonstruovaný podnik si zachovává teplo a autenticitu horské tradice, nabízí prostředí, kde se každý host cítí jako doma. Přírodní dřevěný nábytek a pečlivě navržené detaily vytvářejí dokonalou atmosféru pro nezapomenutelné chvíle.",
    AL: "Lokali rinovuar i gatshëm t'ju mbahet nga tepër dhe nga oshtinë e tradicioneve të planinave, duke ofruar një mjedisje ku çdo vizitor se duhet si në shtëpia. Mobiliat e drejtshënë dhe detajet e paqartëshme krijojnë atmosferë të perfekte për momentet e paqartëshme.",
  },
  "atmosphere.description2": {
    IT: "Dalla colazione al dopocena, vi accompagniamo con prodotti selezionati del territorio, vini pregiati e specialità che celebrano i sapori autentici della nostra terra.",
    EN: "From breakfast to after-dinner, we accompany you with selected local products, fine wines and specialties that celebrate the authentic flavors of our land.",
    DE: "Vom Frühstück bis zum Digestif begleiten wir Sie mit ausgewählten regionalen Produkten, edlen Weinen und Spezialitäten, die die authentischen Aromen unserer Heimat feiern.",
    BS: "Od doručka do večere, pratimo vas odabranim lokalnim proizvodima, finim vinima i specijalitetima koji slave autentične okuse naše zemlje.",
    RU: "От завтрака до ужина мы сопровождаем вас отборными местными продуктами, изысканными винами и деликатесами, которые прославляют подлинные вкусы нашей земли.",
    CZ: "Od snídaně po večeři vás doprovázíme vybranými místními produkty, kvalitními víny a specialitami, které oslavují autentické chutě naší země.",
    AL: "Nga mëngjesi deri në veprimtari, ju shoqëruam me produktet e zgjedhur nga vendi, vinat e mirë dhe specialitetet që flasojnë vlerat e vetme të vendit tanë.",
  },
  "menu.title": {
    IT: "Il Nostro Menu",
    EN: "Our Menu",
    DE: "Unsere Speisekarte",
    BS: "Naš meni",
    RU: "Наше меню",
    CZ: "Naše menu",
    AL: "Menyja jonë",
  },
  "menu.description": {
    IT: "Scoprite i sapori autentici della tradizione montana attraverso i nostri piatti preparati con ingredienti freschi e di qualità del territorio.",
    EN: "Discover the authentic flavors of mountain tradition through our dishes prepared with fresh, quality local ingredients.",
    DE: "Entdecken Sie die authentischen Aromen der Bergtradition durch unsere Gerichte, die mit frischen, hochwertigen regionalen Zutaten zubereitet werden.",
    BS: "Otkrijte autentične okuse planinske tradicije kroz naše jela pripremljena sa svježim, kvalitetnim lokalnim sastojcima.",
    RU: "Откройте для себя подлинные вкусы горных традиций через наши блюда, приготовленные из свежих, качественных местных ингредиентов.",
    CZ: "Objevte autentické chutě horské tradice prostřednictvím našich jídel připravených z čerstvých, kvalitních místních ingrediencí.",
    AL: "Zbuloni vlerat e vetme të tradicioneve të planinave përmes dishave tanë të parapetuar me sastojët e frasha dhe të cilësuar nga vendi.",
  },
  "menu.antipasti": {
    IT: "Antipasti",
    EN: "Appetizers",
    DE: "Vorspeisen",
    BS: "Predjela",
    RU: "Закуски",
    CZ: "Předkrmy",
    AL: "Antipasti",
  },
  "menu.primi": {
    IT: "Primi Piatti",
    EN: "First Courses",
    DE: "Erste Gänge",
    BS: "Prva jela",
    RU: "Первые блюда",
    CZ: "První chody",
    AL: "Primi Piatti",
  },
  "menu.secondi": {
    IT: "Secondi Piatti",
    EN: "Main Courses",
    DE: "Hauptgerichte",
    BS: "Glavna jela",
    RU: "Основные блюда",
    CZ: "Hlavní chody",
    AL: "Secondi Piatti",
  },
  "menu.contorni": {
    IT: "Contorni",
    EN: "Side Dishes",
    DE: "Beilagen",
    BS: "Prilozi",
    RU: "Гарниры",
    CZ: "Přílohy",
    AL: "Contorni",
  },
  "menu.bevande": {
    IT: "Bevande",
    EN: "Beverages",
    DE: "Getränke",
    BS: "Pića",
    RU: "Напитки",
    CZ: "Nápoje",
    AL: "Beverages",
  },
  "menu.birre": {
    IT: "Birre",
    EN: "Beers",
    DE: "Biere",
    BS: "Piva",
    RU: "Пиво",
    CZ: "Piva",
    AL: "Birra",
  },
  "menu.dessert": {
    IT: "Dessert",
    EN: "Dessert",
    DE: "Dessert",
    BS: "Deserti",
    RU: "Десерты",
    CZ: "Dezerty",
    AL: "Ëmbëlsira",
  },
  "menu.bambini": {
    IT: "Per i più piccoli",
    EN: "For Kids",
    DE: "Für Kinder",
    BS: "Za djecu",
    RU: "Для детей",
    CZ: "Pro děti",
    AL: "Për fëmijë",
  },
  "menu.caffetteria": {
    IT: "Caffetteria",
    EN: "Coffee Bar",
    DE: "Cafeteria",
    BS: "Kafeterija",
    RU: "Кофейня",
    CZ: "Kavárna",
    AL: "Kafeteria",
  },
  "menu.liquori": {
    IT: "Liquori",
    EN: "Liqueurs",
    DE: "Liköre",
    BS: "Likeri",
    RU: "Ликеры",
    CZ: "Likéry",
    AL: "Likere",
  },
  "gallery.title": {
    IT: "Galleria",
    EN: "Gallery",
    DE: "Galerie",
    BS: "Galerija",
    RU: "Галерея",
    CZ: "Galerie",
    AL: "Galeria",
  },
  "gallery.description": {
    IT: "Un viaggio visivo attraverso i nostri piatti e l'atmosfera unica del nostro ristorante.",
    EN: "A visual journey through our dishes and the unique atmosphere of our restaurant.",
    DE: "Eine visuelle Reise durch unsere Gerichte und die einzigartige Atmosphäre unseres Restaurants.",
    BS: "Put vizualisht nëpër dishave tanë dhe atmosferën unikë të restorantit tanë.",
    RU: "Визуальное путешествие по нашим блюдам и уникальной атмосфере нашего ресторана.",
    CZ: "Vizuální cesta našimi jídly a jedinečnou atmosférou naší restaurace.",
    AL: "Një udhëhtje vizualisht nëpër dishave tanë dhe atmosferën unikë të restorantit tanë.",
  },
  "contact.title": {
    IT: "Contatti",
    EN: "Contact",
    DE: "Kontakt",
    BS: "Kontakt",
    RU: "Контакты",
    CZ: "Kontakt",
    AL: "Kontakti",
  },
  "contact.description": {
    IT: "Siamo qui per accogliervi e rendere speciale ogni vostro momento con noi.",
    EN: "We are here to welcome you and make every moment with us special.",
    DE: "Wir sind hier, um Sie willkommen zu heißen und jeden Moment mit uns besonders zu machen.",
    BS: "Tu smo da vas dočekamo i učinimo svaki trenutak s nama posebnim.",
    RU: "Мы здесь, чтобы приветствовать вас и сделать каждый момент с нами особенным.",
    CZ: "Jsme tu, abychom vás přivítali a učinili každý okamžik s námi výjimečným.",
    AL: "Janë tani për të presë dhe të bërë çdo moment të tuaj të vërtetë me ne.",
  },
  "contact.address": {
    IT: "Indirizzo",
    EN: "Address",
    DE: "Adresse",
    BS: "Adresa",
    RU: "Адрес",
    CZ: "Adresa",
    AL: "Adresa",
  },
  "contact.hours": {
    IT: "Orari",
    EN: "Hours",
    DE: "Öffnungszeiten",
    BS: "Radno vrijeme",
    RU: "Часы работы",
    CZ: "Otevírací doba",
    AL: "Orari",
  },
  "contact.phone": {
    IT: "Telefono & WhatsApp",
    EN: "Phone & WhatsApp",
    DE: "Telefon & WhatsApp",
    BS: "Telefon & WhatsApp",
    RU: "Телефон и WhatsApp",
    CZ: "Telefon & WhatsApp",
    AL: "Telefon & WhatsApp",
  },
  "contact.follow": {
    IT: "Seguici",
    EN: "Follow Us",
    DE: "Folgen Sie uns",
    BS: "Pratite nas",
    RU: "Следите за нами",
    CZ: "Sledujte nás",
    AL: "Sledoni ne",
  },
  "contact.priceRange": {
    IT: "Fascia di Prezzo",
    EN: "Price Range",
    DE: "Preisklasse",
    BS: "Cjenovni razred",
    RU: "Ценовая категория",
    CZ: "Cenová kategorie",
    AL: "Ranësia e çmimit",
  },
  "contact.perPerson": {
    IT: "per persona",
    EN: "per person",
    DE: "pro Person",
    BS: "po osobi",
    RU: "на человека",
    CZ: "na osobu",
    AL: "për person",
  },
  "contact.reservationInfo": {
    IT: "Per prenotazioni e informazioni, contattateci via WhatsApp al numero sopra indicato. Saremo lieti di accogliervi nella nostra atmosfera montana autentica.",
    EN: "For reservations and information, contact us via WhatsApp at the number above. We will be happy to welcome you to our authentic mountain atmosphere.",
    DE: "Für Reservierungen und Informationen kontaktieren Sie uns über WhatsApp unter der oben angegebenen Nummer. Wir freuen uns darauf, Sie in unserer authentischen Bergatmosphäre willkommen zu heißen.",
    BS: "Za rezervacije i informacije kontaktirajte nas putem WhatsApp-a na gore navedeni broj. Rado ćemo vas dočekati u našoj autentičnoj planinskoj atmosferi.",
    RU: "Для бронирования и информации свяжитесь с нами через WhatsApp по указанному выше номеру. Мы будем рады приветствовать вас в нашей подлинной горной атмосфере.",
    CZ: "Pro rezervace a informace nás kontaktujte přes WhatsApp na výše uvedeném čísle. Rádi vás přivítáme v naší autentické horské atmosféře.",
    AL: "Për rezervimet dhe informacionet, ju lutem kontaktoni ne përmes WhatsApp-it në numrin e mësipërshme. Rado do t'ju pranojmë në atmosferën tonë të vetme të planinave.",
  },
  "footer.tagline": {
    IT: "Tradizione e sapori autentici della montagna",
    EN: "Authentic mountain traditions and flavors",
    DE: "Authentische Bergtraditionen und Aromen",
    BS: "Autentične planinske tradicije i okusi",
    RU: "Подлинные горные традиции и вкусы",
    CZ: "Autentické horské tradice a chutě",
    AL: "Tradicione dhe vlerat e vetme të planinave",
  },
  "footer.rights": {
    IT: "© 2024 La Busa del Sauc. Tutti i diritti riservati.",
    EN: "© 2024 La Busa del Sauc. All rights reserved.",
    DE: "© 2024 La Busa del Sauc. Alle Rechte vorbehalten.",
    BS: "© 2024 La Busa del Sauc. Sva prava pridržana.",
    RU: "© 2024 La Busa del Sauc. Все права защищены.",
    CZ: "© 2024 La Busa del Sauc. Všechna práva vyhrazena.",
    AL: "© 2024 La Busa del Sauc. tëra të drejtave të rezervuar.",
  },
  "hours.weekend": {
    IT: "Domenica, mercoledì-sabato: 10:30-22:30",
    EN: "Sunday, Wednesday-Saturday: 10:30-22:30",
    DE: "Sonntag, Mittwoch-Samstag: 10:30-22:30",
    BS: "Nedjelja, srijeda-subota: 10:30-22:30",
    RU: "Воскресенье, среда-суббота: 10:30-22:30",
    CZ: "Neděle, středa-sobota: 10:30-22:30",
    AL: "E diel, e mërkurë-e shtunë: 10:30-22:30",
  },
  "hours.weekdays": {
    IT: "Lunedì e martedì: chiuso",
    EN: "Monday and Tuesday: closed",
    DE: "Montag und Dienstag: geschlossen",
    BS: "Ponedjeljak i utorak: zatvoreno",
    RU: "Понедельник и вторник: закрыто",
    CZ: "Pondělí a úterý: zavřeno",
    AL: "E hënë dhe e martë: mbyllur",
  },
  "hours.openDays": {
    IT: "Domenica, mercoledì-sabato",
    EN: "Sunday, Wednesday-Saturday",
    DE: "Sonntag, Mittwoch-Samstag",
    BS: "Nedjelja, srijeda-subota",
    RU: "Воскресенье, среда-суббота",
    CZ: "Neděle, středa-sobota",
    AL: "E diel, e mërkurë-e shtunë",
  },
  "hours.closedDays": {
    IT: "Lunedì e martedì chiuso",
    EN: "Closed Monday and Tuesday",
    DE: "Montag und Dienstag geschlossen",
    BS: "Zatvoreno ponedjeljkom i utorkom",
    RU: "Закрыто в понедельник и вторник",
    CZ: "V pondělí a úterý zavřeno",
    AL: "Mbyllur të hënën dhe të martën",
  },
  "hours.openDaysAugust": {
    IT: "Agosto: tutti i giorni",
    EN: "August: every day",
    DE: "August: täglich",
    BS: "Avgust: svaki dan",
    RU: "Август: ежедневно",
    CZ: "Srpen: každý den",
    AL: "Gusht: çdo ditë",
  },
  "hours.augustNote": {
    IT: "Aperto tutti i giorni per tutto il mese di agosto",
    EN: "Open every day throughout August",
    DE: "Den ganzen August über täglich geöffnet",
    BS: "Otvoreno svaki dan tijekom cijelog avgusta",
    RU: "Открыто каждый день весь август",
    CZ: "Otevřeno každý den po celý srpen",
    AL: "Hapur çdo ditë gjatë gjithë muajit gusht",
  },
  "hours.augustUpcoming": {
    IT: "Ad agosto siamo aperti tutti i giorni",
    EN: "In August we are open every day",
    DE: "Im August sind wir täglich geöffnet",
    BS: "U avgustu smo otvoreni svaki dan",
    RU: "В августе мы открыты каждый день",
    CZ: "V srpnu máme otevřeno každý den",
    AL: "Në gusht jemi hapur çdo ditë",
  },
  "hours.summaryAugust": {
    IT: "Agosto: aperto tutti i giorni 10:30-22:30",
    EN: "August: open every day 10:30-22:30",
    DE: "August: täglich geöffnet 10:30-22:30",
    BS: "Avgust: otvoreno svaki dan 10:30-22:30",
    RU: "Август: открыто ежедневно 10:30-22:30",
    CZ: "Srpen: otevřeno každý den 10:30-22:30",
    AL: "Gusht: hapur çdo ditë 10:30-22:30",
  },
  "hours.time": {
    IT: "10:30-22:30",
    EN: "10:30-22:30",
    DE: "10:30-22:30",
    BS: "10:30-22:30",
    RU: "10:30-22:30",
    CZ: "10:30-22:30",
    AL: "10:30-22:30",
  },
  "hours.summary": {
    IT: "Aperto 10:30-22:30, chiuso lunedì e martedì",
    EN: "Open 10:30-22:30, closed Monday and Tuesday",
    DE: "Geöffnet 10:30-22:30, Montag und Dienstag geschlossen",
    BS: "Otvoreno 10:30-22:30, zatvoreno ponedjeljkom i utorkom",
    RU: "Открыто 10:30-22:30, закрыто понедельник и вторник",
    CZ: "Otevřeno 10:30-22:30, zavřeno pondělí a úterý",
    AL: "Hapur 10:30-22:30, mbyllur të hënën dhe të martën",
  },
  "status.open": {
    IT: "Aperto ora",
    EN: "Open now",
    DE: "Jetzt geöffnet",
    BS: "Trenutno otvoreno",
    RU: "Сейчас открыто",
    CZ: "Nyní otevřeno",
    AL: "Hapur tani",
  },
  "status.closed": {
    IT: "Chiuso ora",
    EN: "Closed now",
    DE: "Jetzt geschlossen",
    BS: "Trenutno zatvoreno",
    RU: "Сейчас закрыто",
    CZ: "Nyní zavřeno",
    AL: "Mbyllur tani",
  },
  "action.call": {
    IT: "Chiama",
    EN: "Call",
    DE: "Anrufen",
    BS: "Pozovi",
    RU: "Позвонить",
    CZ: "Volat",
    AL: "Telefono",
  },
  "action.directions": {
    IT: "Indicazioni",
    EN: "Directions",
    DE: "Route",
    BS: "Upute",
    RU: "Маршрут",
    CZ: "Trasa",
    AL: "Udhëzime",
  },
  "action.openMaps": {
    IT: "Apri su Google Maps",
    EN: "Open in Google Maps",
    DE: "In Google Maps öffnen",
    BS: "Otvori u Google Maps",
    RU: "Открыть в Google Maps",
    CZ: "Otevřít v Google Maps",
    AL: "Hap në Google Maps",
  },
  "whatsapp.info": {
    IT: "Per prenotazioni via WhatsApp",
    EN: "For WhatsApp reservations",
    DE: "Für WhatsApp-Reservierungen",
    BS: "Za rezervacije putem WhatsApp-a",
    RU: "Для бронирования через WhatsApp",
    CZ: "Pro rezervace přes WhatsApp",
    AL: "Për rezervimet përmes WhatsApp-it",
  },
  "special.label": {
    IT: "Serata di pesce",
    EN: "Fish night",
    DE: "Fischabend",
    BS: "Riblje veče",
    RU: "Рыбный вечер",
    CZ: "Rybí večer",
    AL: "Mbrëmje peshku",
  },
  "special.reservationOnly": {
    IT: "Solo su prenotazione",
    EN: "By reservation only",
    DE: "Nur mit Reservierung",
    BS: "Samo uz rezervaciju",
    RU: "Только по предварительному бронированию",
    CZ: "Pouze na rezervaci",
    AL: "Vetëm me rezervim",
  },
  "special.book": {
    IT: "Prenota su WhatsApp",
    EN: "Book on WhatsApp",
    DE: "Über WhatsApp reservieren",
    BS: "Rezerviši putem WhatsApp-a",
    RU: "Забронировать в WhatsApp",
    CZ: "Rezervovat přes WhatsApp",
    AL: "Rezervo në WhatsApp",
  },
  "special.brezzaMarina.title": {
    IT: "Brezza Marina in Alta Quota",
    EN: "Brezza Marina in Alta Quota",
    DE: "Brezza Marina in Alta Quota",
    BS: "Brezza Marina in Alta Quota",
    RU: "Brezza Marina in Alta Quota",
    CZ: "Brezza Marina in Alta Quota",
    AL: "Brezza Marina in Alta Quota",
  },
  "special.brezzaMarina.tartare.name": {
    IT: "Tartare di Mare",
    EN: "Sea Tartare",
    DE: "Tatar vom Meer",
    BS: "Tartar od plodova mora",
    RU: "Тартар из морепродуктов",
    CZ: "Tatarák z mořských plodů",
    AL: "Tartar deti",
  },
  "special.brezzaMarina.tartare.description": {
    IT: "Seppia e piovra con concassé di pomodorini freschi e un delicato condimento agrumato, per esaltare la freschezza e l'equilibrio dei sapori del mare.",
    EN: "Cuttlefish and octopus with a concassé of fresh cherry tomatoes and a delicate citrus dressing, bringing out the freshness and balance of the flavours of the sea.",
    DE: "Sepia und Oktopus mit Concassé von frischen Kirschtomaten und einem zarten Zitrusdressing, das die Frische und Ausgewogenheit der Meeresaromen hervorhebt.",
    BS: "Sipa i hobotnica s concasséom od svježih cherry rajčica i nježnim citrusnim preljevom, koji naglašava svježinu i ravnotežu okusa mora.",
    RU: "Каракатица и осьминог с конкассе из свежих томатов черри и деликатной цитрусовой заправкой, подчёркивающей свежесть и баланс морских вкусов.",
    CZ: "Sépie a chobotnice s concassé z čerstvých cherry rajčat a jemnou citrusovou zálivkou, která zvýrazní svěžest a vyváženost mořských chutí.",
    AL: "Sepje dhe oktapod me concassé nga domate qershi të freskëta dhe një salcë delikate me agrume, që nxjerr në pah freskinë dhe ekuilibrin e shijeve të detit.",
  },
  "special.brezzaMarina.pacchero.name": {
    IT: "Mezzo Pacchero alla Busara",
    EN: "Mezzo Pacchero alla Busara",
    DE: "Mezzo Pacchero alla Busara",
    BS: "Mezzo Pacchero alla Busara",
    RU: "Mezzo Pacchero alla Busara",
    CZ: "Mezzo Pacchero alla Busara",
    AL: "Mezzo Pacchero alla Busara",
  },
  "special.brezzaMarina.pacchero.description": {
    IT: "Pasta artigianale avvolta nella tradizionale salsa alla Busara, un incontro intenso di profumi e sapori che richiamano l'Adriatico.",
    EN: "Artisan pasta wrapped in the traditional Busara sauce, an intense meeting of aromas and flavours that recall the Adriatic.",
    DE: "Handwerklich hergestellte Pasta in der traditionellen Busara-Sauce, ein intensives Zusammenspiel von Düften und Aromen der Adria.",
    BS: "Ručno rađena tjestenina u tradicionalnom umaku Busara, intenzivan susret mirisa i okusa koji dozivaju Jadran.",
    RU: "Ремесленная паста в традиционном соусе «бусара» — насыщенная встреча ароматов и вкусов Адриатики.",
    CZ: "Řemeslné těstoviny obalené tradiční omáčkou Busara, intenzivní setkání vůní a chutí připomínajících Jadran.",
    AL: "Makarona artizanale të mbështjella në salcën tradicionale Busara, një takim intensiv aromash dhe shijesh që kujtojnë Adriatikun.",
  },
  "special.brezzaMarina.branzino.name": {
    IT: "Rollè di Branzino",
    EN: "Sea Bass Roulade",
    DE: "Wolfsbarsch-Roulade",
    BS: "Rolada od brancina",
    RU: "Рулет из сибаса",
    CZ: "Roláda z mořského vlka",
    AL: "Rrotull levreku",
  },
  "special.brezzaMarina.branzino.description": {
    IT: "Servito con verdurine julienne croccanti e una vellutata crema di patate affumicate.",
    EN: "Served with crisp julienne vegetables and a velvety smoked potato cream.",
    DE: "Serviert mit knackigem Julienne-Gemüse und einer samtigen Creme aus geräucherten Kartoffeln.",
    BS: "Poslužena s hrskavim julienne povrćem i baršunastom kremom od dimljenog krumpira.",
    RU: "Подаётся с хрустящими овощами жюльен и бархатным кремом из копчёного картофеля.",
    CZ: "Podávaná s křupavou zeleninou julienne a sametovým krémem z uzených brambor.",
    AL: "Shërbehet me perime julienne krokante dhe një krem kadifeje me patate të tymosura.",
  },
  "special.brezzaMarina.dolce.name": {
    IT: "Il Richiamo della Montagna",
    EN: "The Call of the Mountain",
    DE: "Der Ruf des Berges",
    BS: "Zov planine",
    RU: "Зов горы",
    CZ: "Volání hor",
    AL: "Thirrja e malit",
  },
  "special.brezzaMarina.dolce.description": {
    IT: "Dolce creazione del nostro chef, ispirata ai profumi e alle emozioni dell'alta quota.",
    EN: "A sweet creation by our chef, inspired by the scents and emotions of the high peaks.",
    DE: "Eine süße Kreation unseres Küchenchefs, inspiriert von den Düften und Emotionen der Höhenlagen.",
    BS: "Slatka kreacija našeg chefa, nadahnuta mirisima i emocijama visokih planina.",
    RU: "Сладкое творение нашего шефа, вдохновлённое ароматами и эмоциями высокогорья.",
    CZ: "Sladká kreace našeho šéfkuchaře, inspirovaná vůněmi a emocemi vysokých hor.",
    AL: "Një krijim i ëmbël i shefit tonë, i frymëzuar nga aromat dhe emocionet e lartësive.",
  },
  "menu.items.tagliere": {
    IT: "Tagliere di affettati misti con giardiniera",
    EN: "Mixed cold cuts platter with pickled vegetables",
    DE: "Gemischte Aufschnittplatte mit eingelegtem Gemüse",
    BS: "Mješovita ploča narezaka s ukiseljenim povrćem",
    RU: "Ассорти мясных деликатесов с маринованными овощами",
    CZ: "Míchané uzeniny s nakládanou zeleninou",
    AL: "Ploqë e mësivit të mështit me povrçë të ukisht",
  },
  "menu.items.formaggi": {
    IT: "Selezione di formaggi con mostarda ai fichi",
    EN: "Selection of cheeses with fig mustard",
    DE: "Käseauswahl mit Feigensenf",
    BS: "Izbor sireva s mostardom od smokava",
    RU: "Ассорти сыров с инжирной горчицей",
    CZ: "Výběr sýrů s fíkovou hořčicí",
    AL: "Përzgjedhje së sërumit me hořčicë të figave",
  },
  "menu.items.tartare": {
    IT: "Tartare tradizionale (senape, scalogno, capperi, olive, acciughe e worchester), contorno del giorno e i nostri crostini",
    EN: "Traditional tartare (mustard, shallot, capers, olives, anchovies and worcester), side dish of the day and our croutons",
    DE: "Traditionelles Tatar (Senf, Schalotten, Kapern, Oliven, Sardellen und Worcester), Tagesbeilage und unsere Croutons",
    BS: "Tradicionalni tartar (senf, ljutika, kapari, masline, inćuni i worcester), prilog dana i naši krostini",
    RU: "Традиционный тартар (горчица, лук-шалот, каперсы, оливки, анчоусы и вустер), гарнир дня и наши гренки",
    CZ: "Tradiční tatarák (hořčice, šalotka, kapary, olivy, ančovičky a worcester), příloha dne a naše krutony",
    AL: "Tartare tradicional me garniturën e ditës dhe krutonët tanë",
  },
  "menu.items.flan": {
    IT: "Flan di zucca, fonduta di montasio, speck e spinacini",
    EN: "Pumpkin flan, montasio fondue, speck and baby spinach",
    DE: "Kürbisflan, Montasio-Fondue, Speck und Babyspinat",
    BS: "Flan od bundeve, montasio fondue, speck i baby špinat",
    RU: "Тыквенный флан, фондю из монтазио, спек и бэби-шпинат",
    CZ: "Dýňový flan, fondue z montasia, speck a baby špenát",
    AL: "Flan kungulli, fondue montasio, speck dhe spinaq i vogël",
  },
  "menu.items.gazpacho": {
    IT: "Gazpacho della Busa",
    EN: "Busa gazpacho",
    DE: "Gazpacho della Busa",
    BS: "Gazpacho della Busa",
    RU: "Гаспачо della Busa",
    CZ: "Gazpacho della Busa",
    AL: "Gazpacho della Busa",
  },
  "menu.items.pappardelle": {
    IT: "Pappardelle, ragù di cinghiale in rosso e fonduta di parmigiano",
    EN: "Pappardelle, wild boar ragù in red wine and parmesan fondue",
    DE: "Pappardelle, Wildschwein-Ragout in Rotwein und Parmesan-Fondue",
    BS: "Pappardelle, ragù od divlje svinje u crvenom vinu i parmezan fondue",
    RU: "Паппарделле, рагу из кабана в красном вине и фондю из пармезана",
    CZ: "Pappardelle, ragù z divočáka v červeném víně a parmezánové fondue",
    AL: "Pappardelle, ragù nga derri i egër në verë të kuqe dhe fondue parmigiano",
  },
  "menu.items.zuppa": {
    IT: "Zuppa del giorno",
    EN: "Soup of the day",
    DE: "Tagessuppe",
    BS: "Dnevna juha",
    RU: "Суп дня",
    CZ: "Denní polévka",
    AL: "Supë e ditës",
  },
  "menu.items.zuppa_cipolle": {
    IT: "Zuppa di cipolle con crostini",
    EN: "Onion soup with croutons",
    DE: "Zwiebelsuppe mit Croutons",
    BS: "Juha od luka s krostinima",
    RU: "Луковый суп с гренками",
    CZ: "Cibulová polévka s krutony",
    AL: "Supë me qepë dhe krutone",
  },
  "menu.items.parmigiana": {
    IT: "Parmigiana di melanzane 2.0",
    EN: "Eggplant parmigiana 2.0",
    DE: "Auberginen-Parmigiana 2.0",
    BS: "Parmigiana od patlidžana 2.0",
    RU: "Пармиджана из баклажанов 2.0",
    CZ: "Lilková parmigiana 2.0",
    AL: "Parmigiana me patëllxhan 2.0",
  },
  "menu.items.gnocchi": {
    IT: "Gnocchi fatti in casa ai porcini e salsiccia",
    EN: "Homemade gnocchi with porcini and sausage",
    DE: "Hausgemachte Gnocchi mit Steinpilzen und Wurst",
    BS: "Domaći njoki s vrganjima i kobasicom",
    RU: "Домашние ньокки с белыми грибами и колбасой",
    CZ: "Domácí gnocchi s hříbky a klobásou",
    AL: "Njoki të bërë në shtëpi me porcini dhe salsicë",
  },
  "menu.items.cervo": {
    IT: "Cervo brasato con polenta",
    EN: "Braised venison with polenta",
    DE: "Geschmorter Hirsch mit Polenta",
    BS: "Dinstana srnetina s polentom",
    RU: "Тушеная оленина с полентой",
    CZ: "Dušená srnčí s polentou",
    AL: "Cervo brasato me polenta",
  },
  "menu.items.frico": {
    IT: "Frico con polenta",
    EN: "Frico with polenta",
    DE: "Frico mit Polenta",
    BS: "Frico s polentom",
    RU: "Фрико с полентой",
    CZ: "Frico s polentou",
    AL: "Frico me polenta",
  },
  "menu.items.tagliata": {
    IT: "Tagliata di manzo con contorno del giorno",
    EN: "Sliced beef with side dish of the day",
    DE: "Geschnittenes Rindfleisch mit Beilage des Tages",
    BS: "Narezana govedina s prilogom dana",
    RU: "Нарезанная говядина с гарниром дня",
    CZ: "Krájené hovězí s přílohou dne",
    AL: "Tagliata të lopës me guarnicion të ditës",
  },
  "menu.items.ribs": {
    IT: "Ribs BBQ con patate",
    EN: "BBQ ribs with potatoes",
    DE: "BBQ-Ribs mit Kartoffeln",
    BS: "BBQ rebarca s krompirom",
    RU: "Ребрышки BBQ с картофелем",
    CZ: "BBQ žebra s bramborami",
    AL: "Ribs BBQ me patate",
  },
  "menu.items.patate": {
    IT: "Patate fritte",
    EN: "French fries",
    DE: "Pommes frites",
    BS: "Pomfrit",
    RU: "Картофель фри",
    CZ: "Hranolky",
    AL: "Pomfrit",
  },
  "menu.items.funghi": {
    IT: "Funghi misti",
    EN: "Mixed mushrooms",
    DE: "Gemischte Pilze",
    BS: "Mješane gljive",
    RU: "Ассорти грибов",
    CZ: "Míchané houby",
    AL: "Mushrooms të mështit",
  },
  "menu.items.spinaci": {
    IT: "Spinaci stufati",
    EN: "Stewed spinach",
    DE: "Geschmorter Spinat",
    BS: "Dinstani špinat",
    RU: "Тушеный шпинат",
    CZ: "Dušený špenát",
    AL: "Spinaci të stufuara",
  },
  "menu.items.insalata": {
    IT: "Insalata mista",
    EN: "Mixed salad",
    DE: "Gemischter Salat",
    BS: "Mješana salata",
    RU: "Смешанный салат",
    CZ: "Míchený salát",
    AL: "Insalata të mështit",
  },
  "menu.items.dessert": {
    IT: "Dessert",
    EN: "Dessert",
    DE: "Dessert",
    BS: "Desert",
    RU: "Десерт",
    CZ: "Dezert",
    AL: "Ëmbëlsirë",
  },
  "menu.items.coperto": {
    IT: "Coperto",
    EN: "Cover charge",
    DE: "Gedeck",
    BS: "Kuvert",
    RU: "Сервировка",
    CZ: "Servisní poplatek",
    AL: "Kuvertë",
  },
  "menu.price.from6": {
    IT: "da €6,00",
    EN: "from €6.00",
    DE: "ab €6,00",
    BS: "od €6,00",
    RU: "от €6,00",
    CZ: "od €6,00",
    AL: "nga €6,00",
  },
  "menu.items.pasta_pomodoro": {
    IT: "Pasta al pomodoro",
    EN: "Pasta with tomato sauce",
    DE: "Pasta mit Tomatensauce",
    BS: "Pasta s paradajz sosom",
    RU: "Паста с томатным соусом",
    CZ: "Těstoviny s rajčatovou omáčkou",
    AL: "Pasta me salcë domate",
  },
  "menu.items.wurstel_patate": {
    IT: "Wurstel con patate fritte",
    EN: "Wurstel with fries",
    DE: "Würstel mit Pommes frites",
    BS: "Hrenovke s pomfritom",
    RU: "Сосиски с картофелем фри",
    CZ: "Párek s hranolky",
    AL: "Wurstel me patate të skuqura",
  },
  "menu.items.cotoletta_patate": {
    IT: "Cotoletta con patate fritte",
    EN: "Cutlet with fries",
    DE: "Schnitzel mit Pommes frites",
    BS: "Kotlet s pomfritom",
    RU: "Котлета с картофелем фри",
    CZ: "Řízek s hranolky",
    AL: "Kotoletta me patate të skuqura",
  },
  "menu.items.acqua": {
    IT: "Acqua 0,5",
    EN: "Water 0.5L",
    DE: "Wasser 0,5L",
    BS: "Voda 0,5L",
    RU: "Вода 0,5 л",
    CZ: "Voda 0,5L",
    AL: "Ujë 0,5L",
  },
  "menu.items.succhi": {
    IT: "Succhi di frutta",
    EN: "Fruit juices",
    DE: "Fruchtsäfte",
    BS: "Voćni sokovi",
    RU: "Фруктовые соки",
    CZ: "Ovocné džusy",
    AL: "Lëngje frutash",
  },
  "menu.items.coca": {
    IT: "Coca cola, Coca zero",
    EN: "Coca-Cola, Coke Zero",
    DE: "Coca-Cola, Coca Zero",
    BS: "Coca-Cola, Coca Zero",
    RU: "Coca-Cola, Coca Zero",
    CZ: "Coca-Cola, Coca Zero",
    AL: "Coca-Cola, Coca Zero",
  },
  "menu.items.fanta": {
    IT: "Fanta, Lemonsoda",
    EN: "Fanta, Lemonsoda",
    DE: "Fanta, Lemonsoda",
    BS: "Fanta, Lemonsoda",
    RU: "Fanta, Lemonsoda",
    CZ: "Fanta, Lemonsoda",
    AL: "Fanta, Lemonsoda",
  },
  "menu.items.the_freddo": {
    IT: "The limone/pesca",
    EN: "Lemon/peach iced tea",
    DE: "Eistee Zitrone/Pfirsich",
    BS: "Ledeni čaj limun/breskva",
    RU: "Холодный чай лимон/персик",
    CZ: "Ledový čaj citron/broskev",
    AL: "Çaj i ftohtë limon/pjeshkë",
  },
  "menu.items.crodino": {
    IT: "Crodino, Gingerino",
    EN: "Crodino, Gingerino",
    DE: "Crodino, Gingerino",
    BS: "Crodino, Gingerino",
    RU: "Crodino, Gingerino",
    CZ: "Crodino, Gingerino",
    AL: "Crodino, Gingerino",
  },
  "menu.items.spritz_aperol": {
    IT: "Spritz Aperol",
    EN: "Aperol Spritz",
    DE: "Aperol Spritz",
    BS: "Aperol Spritz",
    RU: "Аперол Шприц",
    CZ: "Aperol Spritz",
    AL: "Aperol Spritz",
  },
  "menu.items.spritz_campari": {
    IT: "Spritz Campari",
    EN: "Campari Spritz",
    DE: "Campari Spritz",
    BS: "Campari Spritz",
    RU: "Кампари Шприц",
    CZ: "Campari Spritz",
    AL: "Campari Spritz",
  },
  "menu.items.birra_egg": {
    IT: "Birra Eggenberger 0,25",
    EN: "Eggenberger Beer 0.25L",
    DE: "Eggenberger Bier 0,25L",
    BS: "Eggenberger pivo 0,25L",
    RU: "Пиво Эггенбергер 0,25л",
    CZ: "Eggenberger pivo 0,25L",
    AL: "Birra Eggenberger 0,25L",
  },
  "menu.items.birra_egg_040": {
    IT: "Birra Eggenberger 0,40",
    EN: "Eggenberger Beer 0.40L",
    DE: "Eggenberger Bier 0,40L",
    BS: "Eggenberger pivo 0,40L",
    RU: "Пиво Эггенбергер 0,40л",
    CZ: "Eggenberger pivo 0,40L",
    AL: "Birra Eggenberger 0,40L",
  },
  "menu.items.birra_men_025": {
    IT: "Birra Menabrea 0,25",
    EN: "Menabrea Beer 0.25L",
    DE: "Menabrea Bier 0,25L",
    BS: "Menabrea pivo 0,25L",
    RU: "Пиво Менабреа 0,25л",
    CZ: "Menabrea pivo 0,25L",
    AL: "Birra Menabrea 0,25L",
  },
  "menu.items.birra_men": {
    IT: "Birra Menabrea 0,40",
    EN: "Menabrea Beer 0.40L",
    DE: "Menabrea Bier 0,40L",
    BS: "Menabrea pivo 0,40L",
    RU: "Пиво Менабреа 0,40л",
    CZ: "Menabrea pivo 0,40L",
    AL: "Birra Menabrea 0,40L",
  },
  "menu.items.caffe": {
    IT: "Caffè espresso",
    EN: "Espresso",
    DE: "Espresso",
    BS: "Espresso",
    RU: "Эспрессо",
    CZ: "Espresso",
    AL: "Espresso",
  },
  "menu.items.cappuccino": {
    IT: "Cappuccino",
    EN: "Cappuccino",
    DE: "Cappuccino",
    BS: "Cappuccino",
    RU: "Капучино",
    CZ: "Cappuccino",
    AL: "Cappuccino",
  },
  "menu.items.decaffeinato": {
    IT: "Decaffeinato",
    EN: "Decaffeinated coffee",
    DE: "Entkoffeinierter Kaffee",
    BS: "Kafa bez kofeina",
    RU: "Кофе без кофеина",
    CZ: "Káva bez kofeinu",
    AL: "Kafe pa kafeinë",
  },
  "menu.items.orzo": {
    IT: "D'orzo",
    EN: "Barley coffee",
    DE: "Gerstenkaffee",
    BS: "Ječmena kafa",
    RU: "Ячменный кофе",
    CZ: "Ječná káva",
    AL: "Kafe elbi",
  },
  "menu.items.ginseng": {
    IT: "Ginseng",
    EN: "Ginseng coffee",
    DE: "Ginseng-Kaffee",
    BS: "Ginseng kafa",
    RU: "Кофе с женьшенем",
    CZ: "Ginseng káva",
    AL: "Kafe ginseng",
  },
  "menu.items.caffe_corretto": {
    IT: "Caffè corretto",
    EN: "Corrected coffee",
    DE: "Caffè corretto",
    BS: "Kafa s dodatkom alkohola",
    RU: "Кофе с алкоголем",
    CZ: "Caffè corretto",
    AL: "Kafe corretto",
  },
  "menu.items.the_caldo": {
    IT: "The caldo",
    EN: "Hot tea",
    DE: "Heißer Tee",
    BS: "Topli čaj",
    RU: "Горячий чай",
    CZ: "Horký čaj",
    AL: "Çaj i ngrohtë",
  },
  "menu.items.infusi": {
    IT: "Infusi",
    EN: "Herbal infusions",
    DE: "Aufgüsse",
    BS: "Biljni čajevi",
    RU: "Травяные настои",
    CZ: "Bylinné čaje",
    AL: "Infuzione",
  },
  "menu.items.amari": {
    IT: "Amari",
    EN: "Bitters",
    DE: "Amari",
    BS: "Amari",
    RU: "Амари",
    CZ: "Amari",
    AL: "Amari",
  },
  "menu.items.grappe": {
    IT: "Grappe",
    EN: "Grappa",
    DE: "Grappa",
    BS: "Grappe",
    RU: "Граппа",
    CZ: "Grappa",
    AL: "Grappe",
  },
  "footer.createdBy": {
    IT: "Sito web creato da",
    EN: "Website created by",
    DE: "Website erstellt von",
    BS: "Web stranica kreirana od",
    RU: "Веб-сайт создан",
    CZ: "Webová stránka vytvořena",
    AL: "Faqja e internetit u krijua nga",
  },
  "footer.privacyPolicy": {
    IT: "Privacy Policy",
    EN: "Privacy Policy",
    DE: "Datenschutzrichtlinie",
    BS: "Pravila privatnosti",
    RU: "Политика конфиденциальности",
    CZ: "Zásady ochrany osobních údajů",
    AL: "Politika e privatitetit",
  },
  "footer.cookiePolicy": {
    IT: "Cookie Policy",
    EN: "Cookie Policy",
    DE: "Cookie-Richtlinie",
    BS: "Pravila kolačića",
    RU: "Политика использования файлов cookie",
    CZ: "Zásady používání souborů cookie",
    AL: "Politika e kolaçeve",
  },
  "privacy.title": {
    IT: "Informativa sulla Privacy",
    EN: "Privacy Policy",
    DE: "Datenschutzerklärung",
    BS: "Pravila privatnosti",
    RU: "Политика конфиденциальности",
    CZ: "Zásady ochrany osobních údajů",
    AL: "Politika e privatitetit",
  },
  "privacy.content": {
    IT: "Questo sito web non raccoglie dati personali degli utenti. Utilizziamo solo cookie tecnici necessari per il funzionamento del sito.",
    EN: "This website does not collect personal user data. We only use technical cookies necessary for the site's functionality.",
    DE: "Diese Website sammelt keine persönlichen Benutzerdaten. Wir verwenden nur technische Cookies, die für die Funktionalität der Website erforderlich sind.",
    BS: "Ova web stranica ne prikuplja osobne podatke korisnika. Koristimo samo tehničke kolačiće potrebne za funkcioniranje stranice.",
    RU: "Этот веб-сайт не собирает персональные данные пользователей. Мы используем только технические файлы cookie, необходимые для функционирования сайта.",
    CZ: "Tato webová stránka neshromažďuje osobní údaje uživatelů. Používáme pouze technické soubory cookie nezbytné pro fungování stránky.",
    AL: "Kjo faqe web nuk kolekcionon të dhëna personale të përdoruesve. Përdorim vetëm cookie të teknikësh të nevojshme për funksionimin e faqes.",
  },
  "cookie.title": {
    IT: "Informativa sui Cookie",
    EN: "Cookie Policy",
    DE: "Cookie-Richtlinie",
    BS: "Pravila kolačića",
    RU: "Политика использования файлов cookie",
    CZ: "Zásady používání souborů cookie",
    AL: "Politika e kolaçeve",
  },
  "cookie.content": {
    IT: "Utilizziamo solo cookie tecnici essenziali per il funzionamento del sito. Non utilizziamo cookie di tracciamento o di profilazione.",
    EN: "We only use essential technical cookies for the site's functionality. We do not use tracking or profiling cookies.",
    DE: "Wir verwenden nur wesentliche technische Cookies für die Funktionalität der Website. Wir verwenden keine Tracking- oder Profiling-Cookies.",
    BS: "Koristimo samo osnovne tehničke kolačiće za funkcioniranje stranice. Ne koristimo kolačiće za praćenje ili profiliranje.",
    RU: "Мы используем только основные технические файлы cookie для функционирования сайта. Мы не используем файлы cookie для отслеживания или профилирования.",
    CZ: "Používáme pouze základní technické soubory cookie pro fungování stránky. Nepoužíváme sledovací nebo profilovací soubory cookie.",
    AL: "Përdorim vetëm cookie të teknikësh të oshtinë për funksionimin e faqes. S'përdorim cookie për shqyrtimin ose profilimin.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("IT")

  const t = (key: string): string => {
    return translations[key as keyof typeof translations]?.[language] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { languages }
